### ISSUE TITLE
RESTful API for querying blockchain status

### ISSUE THREAD

**Issue by wileyj** [stacks-network/stacks-core#1229]
something like `/v1/health` with a return code of 200 if everything is synced and up to date.

**Comment by wileyj** [comment]
bump

**Comment by wileyj** [comment]
Still would like to see this, if it's not already been added. 
Currently we have to rely on the TCP port being open, but it'd be preferred to have something like `/v2/health` that tells us the startup has been completed

**Comment by zone117x** [comment]
Not stale? The PR https://github.com/stacks-network/stacks-blockchain/pull/2768 is not merged.

**Comment by wileyj** [comment]
#3729
