### ISSUE TITLE
Microblocks: anti-entropy protocol for unconfirmed microblocks

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-core#2031]
Need to devise and implement a protocol for nodes that are missing some unconfirmed microblocks to go and figure out who else has them, and go fetch them.

The best idea I have so far is to make is so that when relaying a microblock, a node also indicates whether or not it has all of the ancestors of the microblock being relayed.  Then, have recipient nodes request unconfirmed microblocks from the RESTful API if it's missing any microblock ancestors.  This protocol is more efficient than polling neighbors for unconfirmed microblocks -- a node will only pull exactly the data it needs from exactly the neighbors that have it.  Also, this protocol works across multiple microblock forks.

**Comment by jcnelson** [comment]
This hasn't been a problem in practice. Re-open if it becomes a problem.

**Comment by zone117x** [comment]
I think this was closed at a time when microblocks were unintentionally disabled? 
From my observations, it seems this issue still exists, similar to https://github.com/blockstack/stacks-blockchain/issues/2193

If I boot up a new node, it doesn't seem to sync the unconfirmed microblocks or mempool, so takes even longer for an API instance to catch-up to an already running API instance.

**Comment by zone117x** [comment]
I don't think think this has been fixed. Is it still an issue?

**Comment by jcnelson** [comment]
This is no longer relevant since microblocks were disabled in epoch 2.5
