### ISSUE TITLE
Use MMAP for SQLite MARF connections

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#2869]
Enabling MMAP for SQLite MARF connections can have a _huge_ speedup on MARF reads and writes (on SSDs: on spinning disks, improvement is not as noticeable).

Based on the results summarized below, we think that the stacks-node should run with the MMAP pragma enabled.

#### Benchmark: marf_reads

We first ran the `benches/marf_read.rs` test, on an SSD macbook, and observed lower latency with mmap_size.

without mmap:

```
INFO [1633467822.527966] [src/chainstate/stacks/index/marf.rs:183] [main]
 stats, TOTAL_READS: 300000, TOTAL_TIME: 96, reads/s: 3125, TOTAL_WRITES: 300000
```

with mmap

```
INFO [1633467559.064343] [src/chainstate/stacks/index/marf.rs:183] [main]
 stats, TOTAL_READS: 300000, TOTAL_TIME: 55, reads/s: 5454.5454, TOTAL_WRITES: 300000
```

#### Benchmark: block_limit
We then ran the `benches/block_limit` test on an SSD Macbook and observed lower latency with mmap_size.

without mmap 
```
INFO [1633713069.275257] [src/chainstate/stacks/index/marf.rs:183] [main]
 stats, TOTAL_READS: 201000, TOTAL_TIME: 111, reads/s: 1810.8108
```

with mmap
```
INFO [1633713485.667202] [src/chainstate/stacks/index/marf.rs:183] [main]
 stats, TOTAL_READS: 200000, TOTAL_TIME: 54, reads/s: 3703.7036
```

### Mainnet Spinup

We ran an experiment syncing `stacks-node` from scratch. Both cases used SSD hard drive. We synced over the weekend and then took the first 700k data points.

Configuration  | Avg. read time (microseconds)
-- | --
MMAP | 390.24
No MMAP | 1696.12

﻿This charts the moving average (window of 1k reads) of read latency from this data (no-mmap is red, with mmp is blue):

<img width="922" alt="Screen Shot 2021-10-12 at 1 50 52 PM" src="https://user-images.githubusercontent.com/1153552/137012600-80a86bc7-88b6-4c31-b133-8a0dfc3c660c.png">

In this experiment, we see an average _4x_ improvement in the read latency for MARF operations.

**Comment by jcnelson** [comment]
Nice!!

**Comment by jcnelson** [comment]
We're doing this in SIP 012, right?
