### ISSUE TITLE
[sBTC] Validate peg wallet address before storing Peg-in operations

### ISSUE THREAD

**Issue by netrome** [stacks-network/stacks-core#3494]
Once Epoch 3.0 and the updated `.pox` contract for sBTC is in place, we should ensure the peg wallet address is validated before storing any Peg-in operations in the sortition database.

**Comment by jcnelson** [comment]
Temporarily assigning to @netrome.  If we take the [mini sBTC](https://docs.google.com/document/d/1R33gZupJg0KsY-vRZYbVFwTHRmq2BCIvyPIVeY0JyGM/edit#) approach, then this would be handled by the `sbtc-signer` daemon.

**Comment by netrome** [comment]
> Temporarily assigning to @netrome. If we take the [mini sBTC](https://docs.google.com/document/d/1R33gZupJg0KsY-vRZYbVFwTHRmq2BCIvyPIVeY0JyGM/edit#) approach, then this would be handled by the sbtc-signer daemon.

Sounds good. This issue is a reminder for the final stages of sBTC development and is not yet actionable. Do we have a better place to write down notes or a checklist of things we must have done to deliver sBTC completely or is it fine to keep this issue for the time being?

Ping @igorsyl

**Comment by igorsyl** [comment]
> > Temporarily assigning to @netrome. If we take the [mini sBTC](https://docs.google.com/document/d/1R33gZupJg0KsY-vRZYbVFwTHRmq2BCIvyPIVeY0JyGM/edit#) approach, then this would be handled by the sbtc-signer daemon.
> 
> Sounds good. This issue is a reminder for the final stages of sBTC development and is not yet actionable. Do we have a better place to write down notes or a checklist of things we must have done to deliver sBTC completely or is it fine to keep this issue for the time being?
> 
> Ping @igorsyl

@netrome 
Please add to the TODO tab here and add remaining items:
https://docs.google.com/spreadsheets/d/1DwLNts95_4olTXKFI1sV7kF47UlvbpmdADfhUtZ9xJA/edit#gid=681051473

**Comment by netrome** [comment]
> @netrome Please add to the TODO tab here and add remaining items: https://docs.google.com/spreadsheets/d/1DwLNts95_4olTXKFI1sV7kF47UlvbpmdADfhUtZ9xJA/edit#gid=681051473

Done :heavy_check_mark:
