### ISSUE TITLE
Missing anchor blocks not recoverable

### ISSUE THREAD

**Issue by friedger** [stacks-network/stacks-core#3602]
**Describe the bug**

While syncing on mainnet ("stacks-node 2.1.0.0.0 (master:f0ed1b9, release build, linux [x86_64])"), the bitcoin height reached the tip, however, the stacks height stopped to increase at stacks height 90489.

The info shows that 4 anchor blocks are missing:
```
"affirmations":{
"heaviest":"pppppppppppppppppppppppppppppppppppppppppppppppppaaaa",
"stacks_tip":"pppppppppppppppppppppppppppppppppppppppppppppppppaaaa",
"sortition_tip":"pppppppppppppppppppppppppppppppppppppppppppppppppaaaa",
"tentative_best":"pppppppppppppppppppppppppppppppppppppppppppppppppaaaa"},
"last_pox_anchor":{"anchor_block_hash":"0acda68ae3d7d7bd4f494bf5c24b85e9ba7d7307928d00a9cbdd204eeff751ed","anchor_block_txid":"37f011dfa6cb9f6a2b256174274c01a985d93ce315d3e18e295f0d5f6ba0d954"}
```
There is no error in the log.
Adding connection options didn't change anything:
```
[connection_options]
inv_reward_cycles = 6
```

**Steps To Reproduce**
Not clear what is needed to make this happen.

**Expected behavior**
Sync to the stacks tip

**Environment (please complete the following information):**
Using stacks-blockchain-docker

**Additional context**
https://discord.com/channels/621759717756370964/1080394357066190858/1080623928717885602

**Comment by jcnelson** [comment]
I was unable to reproduce this.  I ran the Stacks node on a very slow machine to see if it would accidentally skip processing an anchored block.

We saw this happen a couple of other times.  Restarting the node seemed to fix it.  Did that work for you?

**Comment by friedger** [comment]
I tried that, but did not change for me. I have remove the persistent state by now.

**Comment by friedger** [comment]
If required, open a new issue
