### ISSUE TITLE
[Miner] Microblock miner will occasionally produce a microblock stream fork

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-core#3620]
Thanks to data reported by one of the Stacks blockchain miners, it has come to my attention that the Stacks microblock miner will occasionally produce microblock stream forks.  Per SIP-005, this is a slashable offense.  Other miners correctly produced `PoisonMicroblock` transactions in reaction to discovering the forked stream, but a correct miner should never be producing forked streams in the first place.

**Comment by tycho1212** [comment]
I can confirm that this is often the case on Stacks 2.1 testnet & is leading to many confusing situations during Zest Protocol demos. A fix has high priority for us 🙏

**Comment by jcnelson** [comment]
This is no longer relevant since Stacks 2.5 disabled microblocks
