### ISSUE TITLE
Stacks-node unable to find Bitcoin wallet

### ISSUE THREAD

**Issue by igorsyl** [stacks-network/stacks-core#3651]
Issue initially reported by Yuriy here: https://discord.com/channels/621759717756370964/691807526118883418/1080471748778148031

**Describe the bug**

i use custom wallet on btc node which is loaded from bitcoind.conf
`wallet=bitcoind/data/testnet3/wallets/my_wallet_name/`
2.1 node could find  it while trying to list utxo
it looks like it's trying to use default  'wallet'
is there a way to continue using custom wallet?
`ERRO [1677673080.754803] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:728] [main] Bitcoin RPC failure: error listing utxos Network("Bitcoin RPC: status(500) != success, body is 'Object({\"error\": Object({\"code\": Number(-18), \"message\": String(\"Requested wallet does not exist or is not loaded\")}), \"id\": String(\"stacks\"), \"result\": Null})'")`
wallet is loaded, as bitcoin-cli return correct balance and utxos

don't work either
i've trying everything, changing wallet name to lowercase, set wallet_name=full path to wallet.dat

bitcoin-cli loadwallet shows that wallet is loaded, but stacks-node says Requested wallet does not exist or is not loaded

**Steps To Reproduce**
Please provide detailed instructions (e.g. command line invocation with parameters) to reproduce the behavior.

**Expected behavior**

**Environment (please complete the following information):**

 - OS: [e.g. Ubuntu / Debian]
 - Rust version
 - Version of the appropriate binary / software package

Bitcoin v22.0.0 for testnet
Bitcoin v21.1 for mainnet 
doesn't work for mainnet too

**Additional context**
Please include any relevant stack traces, error messages and logs.

Hi, it doesn't seem to work or i am doing smth. wrong
i loaded the wallet for bitcoind, 
in bitcoind.conf
`wallet=/bitcoind/data/testnet3/wallets/MY_WALLET_NAME/`

in stacks-node config
`wallet_name = "MY_WALLET_NAME"`

when starting the node 
`DEBG [1678156411.470224] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:2147] [main] BitcoinRPC builder 'listunspent': Some("user"):Some("password")@http://127.0.0.1:18332/wallet/MY_WALLET_NAME
ERRO [1678156411.470837] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:728] [main] Bitcoin RPC failure: error listing utxos Network("Bitcoin RPC: status(500) != success, body is 'Object({\"error\": Object({\"code\": Number(-18), \"message\": String(\"Requested wallet does not exist or is not loaded\")}), \"id\": String(\"stacks\"), \"result\": Null})'")`

From Jude:

Hey! Both `master` (2.1.0.0.1) and the 2.1 release from a few weeks ago are stable. In both cases, you'll need to set `always_use_affirmation_maps = false` in the config file in the `[node]` section. I have a PR open that makes this the default, but it is not merged yet

If you are encountering an issue with a smart contract, please include the smart contract code
that demonstrates the issue.

**Comment by diwakergupta** [comment]
Related PR, that does have an integration test for custom wallets: https://github.com/stacks-network/stacks-blockchain/pull/3597

Other relevant threads on Discord:
* https://discord.com/channels/621759717756370964/691807526118883418/1080553018916876329
* https://discord.com/channels/621759717756370964/691807526118883418/1082527670019043328

**Comment by wileyj** [comment]
from reporter:
```
since no default wallet is created by latest bitcoin-core it's quite challenging to spin-up a miner
it requires:
- start a miner in order to create bitcoin default wallet
- stop a miner
- import key to bitcoin wallet
- start a miner so it can track UTXOs in the wallet and start mining
```

will have to test and see if it can be reproduced or resolved.

**Comment by 462960** [comment]
"stacks_tip_height" keeps the pace with the remote, therefore miner node works well as a follower but I don't see "Miner node: starting up, UTXOs found". Wallet has enough tbtc. 
`always_use_affirmation_maps = false
wallet_name="Vlad_2"`
added to config.toml, the miner restarted. Both importaddress and importprivkey are done long before restarting the miner a few times with slightly different .toml.

**Comment by 462960** [comment]
I'm confused by reading "it looks like it's trying to use default 'wallet". When I tried to launch `importaddress or importprivkey` I got smth like "default wallet isn't supported anymore". That's why I created a named wallet, then  `importaddress and importprivkey`. `getwalletinfo` gets the full description except for the address. Is it expected behavior?

**Comment by wileyj** [comment]
https://github.com/stacks-network/stacks-blockchain/pull/3694
