### ISSUE TITLE
CI: Integration tests run on PR opening, but not on updates to the PR

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#3755]
It seems like the integration tests workflow only runs when the PR is opened, but not since updating the PR.

You can see this in action in my rstest PR (#3731)

I *think* it should run on every update (and cancel prior runs), but if that's too much, we should see if we could do something like run-on-approval or some other kind of manual process.

Tagging @wileyj for visibility.

**Comment by wileyj** [comment]
This is being addressed in a fork i'm using to update when workflows are triggered (and what tests to run). draft PR will come soon
