### ISSUE TITLE
Snapshot Database

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#3821]
This structure is responsible for storing and retrieving bitcoin state
relevant to the Nakamato release in a fork-aware fashion. This performs
a similar role to the SortitionDB in Stacks 2.0-2.4, but with a major
difference: PoX forks are not possible in the Nakamoto release,
so "SortitionID"s are no longer necessary. This database is only
concerned with bitcoin forks, and can therefore identify blocks
with bitcoin block hashes.

This struct should be a MARF-backed database capable of storing:

1. Producer candidate commitment transactions
2. Producer announcement transactions
3. Computed data like

These items should be retrievable by:

1. Block height
2. Bitcoin block hash
3. Canonical view

This could be implemented in a few steps:

1. A database that is simply capable of storing the 2 new transaction types
2. A bitcoin block processing routine, to be invoked by the chainstate
   coordinator with new bitcoin block data. Initially, this routine should
   just store the new transactions.
3. A new struct `TermSelection` which is constructed with a method
   `process_commitments`. This method accepts candidate commitment
   transactions over the selection length (10 bitcoin blocks),
   checks that those transactions are all in all valid range,
   and computes the producer set from those transactions. The
   resulting set is conveyed in the `TermSelection` struct.
4. Update to the bitcoin block processing routine of the snapshot
   database to construct and store `TermSelection` results
   when a term boundary is crossed.

**Comment by jcnelson** [comment]
This is done
