### ISSUE TITLE
Stacks Block Storage DB

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#3822]
This structure is responsible for storing Nakamoto blocks.

In order to respond to block queries regarding earlier chain state,
this database will **read** from the prior StacksChainState, but
new block data will be stored in a new database. 

This struct exposes an API for loading and storing blocks on disk, and
any metadata for those blocks, including their Stacker signatures.

It must also include an API for *streaming* data over the network and
RPC interfaces.

Blocks should be fetchable via:

1. The block hash
2. The first snapshot identifier after the block

**Comment by jcnelson** [comment]
This is done
