### ISSUE TITLE
Block push 

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#3825]
This encompasses the work needed to extend the antientropy state
machines to push blocks to neighbors that don’t have them

**Comment by saralab** [comment]
- Ensure Nakamoto nodes stay in sync
- Nodes need to reach the chain tip within 1 round of block production, this is to ensure that the follow-up miner can keep pace with the current miner 
- Consensus logic for dealing with flash blocks and failure to store an aggregate public key
