### ISSUE TITLE
Stacks Block Acceptance

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#3828]
Once a block's metadata has been validated, the `NakamotoStacksState`
needs to evaluate the transactions in the block, applying them
to the materializaed view of the blockchain state.

This is similar to the `append_block()` functionality of the
`StacksChainState` currently. Note that this step must be
fallible -- if a block contains an invalid transaction,
the block cannot be accepted.

**Comment by jcnelson** [comment]
This is done
