### ISSUE TITLE
Update Chains Coordinator to switch to Nakamoto Mode

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#3831]
The chains coordinator must switch operation at the Nakamoto
activation height: instead of processing bitcoin blocks with
the old SortitionDB, it must use the new Snapshot DB, instead
of processing Stacks blocks with the old StacksChainState it must
use the new `NakamotoStacksState`, and it should cease any
operations related to affirmation maps or PoX forks.

**Comment by saralab** [comment]
This has been done
