### ISSUE TITLE
[Testing] two very slow tests can take several hours to run

### ISSUE THREAD

**Issue by wileyj** [stacks-network/stacks-core#3842]
`tests::epoch_21::test_pox_reorg_flap_reward_cycles` - this is a test that takes roughly (with currently defined workflows) about 2 hours before it fails due to timeout. Running the same test with `nextest` hasn't performed much better (i don't have a successful test i can compare to, but i've cancelled this test at 4 hours). The  biggest drawback with this test is that it has to run with a single thread, and i suspect it's CPU bound. 

I'm not sure what in the test could be changed to improve the speed it takes to execute, but if there is anything that can be done (or even make this test as optional in our release ci?) it would make a big difference.

**Comment by wileyj** [comment]
this is something i cannot explain though: <https://github.com/stacks-network/stacks-blockchain/actions/runs/5764522475/job/15630044396>
on occasion, the test will succeed in a reasonable timeframe. 

i suppose it's possible it's not the test itself, but *how* the test is being run. 

i'll share more info as i find it (I'd like to have a successful test myself so i can compare)

**Comment by wileyj** [comment]
```
e$  cargo nextest run \
            --test-threads 1 \
            --run-ignored all \
            --retries 2 \
            --final-status-level fail \
            --archive-file /tmp/test_archive.tar.zst "tests::epoch_21::test_pox_reorg_flap_reward_cycles"
  Extracting 9 binaries and 7 linked paths to /tmp/nextest-archive-Qk85AM
   Extracted 50 files to /tmp/nextest-archive-Qk85AM in 3.27s
    Starting 1 test across 9 binaries (3877 skipped)
        PASS [   0.191s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
------------
     Summary [   0.287s] 1 test run: 1 passed, 3877 skipped
```

i'm more inclined to think the problem here is not the test - i've been running this in action runners exclusively, where the timing is less than ideal. 
locally on a 4cpu system using the same nextest process though....it's quite fast

**Comment by kantai** [comment]
> ```
> $  cargo nextest run \
>             --test-threads 1 \
>             --run-ignored all \
>             --retries 2 \
>             --final-status-level fail \
>             --archive-file /tmp/test_archive.tar.zst "tests::epoch_21::test_pox_reorg_flap_reward_cycles"
>   Extracting 9 binaries and 7 linked paths to /tmp/nextest-archive-Qk85AM
>    Extracted 50 files to /tmp/nextest-archive-Qk85AM in 3.27s
>     Starting 1 test across 9 binaries (3877 skipped)
>         PASS [   0.191s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
> ```

That looks like you need to set the `BITCOIND_TEST=1` envar -- the tests are marked "ignored" _and_ controlled via the BITCOIND_TEST=1 flag.

**Comment by wileyj** [comment]
good point, i don't think i set that on the VM when i ran it. 
shouldn't that test fail in that scenario?

regardless, i was able to run this test in github at an acceptable timeframe (why it's so wildly different each run is just a guess though)
![Screenshot 2023-08-07 at 13 26 46](https://github.com/stacks-network/stacks-blockchain/assets/2847772/a7f550ec-2300-40db-ae99-d60254db11a7)

**Comment by wileyj** [comment]
```
$ cargo nextest run \
            --test-threads 1 \
            --run-ignored all \
            --retries 2 \
            --final-status-level fail \
            --archive-file /tmp/test_archive.tar.zst "tests::epoch_21::test_pox_reorg_flap_reward_cycles"
  Extracting 9 binaries and 7 linked paths to /tmp/nextest-archive-8wr9wI
   Extracted 50 files to /tmp/nextest-archive-8wr9wI in 3.04s
    Starting 1 test across 9 binaries (3877 skipped)
  TRY 1 SLOW [> 60.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>120.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>180.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>240.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>300.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>360.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>420.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>480.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>540.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>600.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>660.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>720.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>780.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>840.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>900.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>960.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>1020.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>1080.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>1140.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
  TRY 1 SLOW [>1200.000s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
        PASS [1227.539s] stacks-node::bin/stacks-node tests::epoch_21::test_pox_reorg_flap_reward_cycles
------------
     Summary [1227.547s] 1 test run: 1 passed (1 slow), 3877 skipped
```
20.45911667 Minutes

I'll run it a few more times to see how consistent it is

**Comment by wileyj** [comment]
seems like around 20 minutes is the gold standard - a few other runs on the VM produced wildly different timings, including one taht took 17 hours before i sigkilled it.

**Comment by kantai** [comment]
I just want to make sure I understand the concerns here.

1. these tests are flaky: sometime they fail.
2. sometimes if they fail, it can take hours.
3. 20 minute "normal" runtime is also too much.

I think Point 2 above is dealt with through the workflow defintion in `bitcoin-tests.yml`:

```yaml
      - name: All integration tests with sampled genesis
        id: bitcoin_integration_tests
        timeout-minutes: 30
        env:
          DOCKER_BUILDKIT: 1
          TEST_NAME: ${{ matrix.test-name }}
        run: docker build -o coverage-output --build-arg test_name=${{ matrix.test-name }} -f ./.github/actions/bitcoin-int-tests/Dockerfile.bitcoin-tests .
```

The tests just get canceled if they run for over 30 minutes.

Points 1 and 3, though, are not resolved by that.

@wileyj -- which of those do you think is a bigger issue?

**Comment by wileyj** [comment]
> I just want to make sure I understand the concerns here.
> 
> 1. these tests are flaky: sometime they fail.
> 2. sometimes if they fail, it can take hours.
> 3. 20 minute "normal" runtime is also too much.
> 
> I think Point 2 above is dealt with through the workflow defintion in `bitcoin-tests.yml`:
> 
> ```yaml
>       - name: All integration tests with sampled genesis
>         id: bitcoin_integration_tests
>         timeout-minutes: 30
>         env:
>           DOCKER_BUILDKIT: 1
>           TEST_NAME: ${{ matrix.test-name }}
>         run: docker build -o coverage-output --build-arg test_name=${{ matrix.test-name }} -f ./.github/actions/bitcoin-int-tests/Dockerfile.bitcoin-tests .
> ```
> 
> The tests just get canceled if they run for over 30 minutes.
> 
> Points 1 and 3, though, are not resolved by that.
> 
> @wileyj -- which of those do you think is a bigger issue?

1 is the biggest concern honestly - since it can take several runs to execute the test successfully. 
i'm not a fan of using that timeout either to be honest - in general, roughly 20 minutes is the time it takes to run successfully, but it can take upwards of 90 minutes and still complete successfully (not sure why this is, i've only seen it happen a handful of times). 

3 is less of a concern i would say - if a test can reliably be run in 20 minutes - then that's how long it takes. 1 and 2 are definitely more problematic, with 1 being the larger issue because the timing varies so wildly. 

that reason alone is why i suggested we remove these 2 tests from being run automatically, but leave them as optional/manual tests that we can run until they can be made more reliable.

**Comment by wileyj** [comment]
@kantai if there's something i could do to generate more verbose output when running these tests to help troubleshoot, i'm happy to do it (i'm typically testing in a fork, but will happily merge upstream changes if it gives us more data)
