### ISSUE TITLE
Nakamoto[Block Validation]: Comms channels for RPC handler and block template/validation

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#3864]
RPC methods for assembling a block template and validating a block must
be asynchronous: block assembly and validation are slow operations, and
the network stack should not stall while processing them. In order to
facilitate this, the RPC handler will send a request for template
generation or block validation over a comms channel. A different
thread will handle the work and then pass the result via the event
interface.

**Comment by jcnelson** [comment]
I think this can be dropped

**Comment by kantai** [comment]
I’m not sure that this can be dropped. Stackers still need to use a block validation endpoints, right?
