### ISSUE TITLE
Nakamotop[Block Validation]: RPC method for block validation

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#3866]
This will be two new RPC methods. The first submits a request to
validate a proposed block. The handler should simply push a
request onto the RPC handler comms channel.

Block validation should accept a stacks block, execute it against
the chain tip, and ensure that it would have executed correctly.

Once validated, the result should be relayed to the event dispatcher
on a new event interface.

**Comment by jcnelson** [comment]
I think this can be dropped

**Comment by kantai** [comment]
Mentioned this elsewhere, but this is still necessary: stacker sign off needs an endpoint for validating the current miner's new blocks.

**Comment by saralab** [comment]
This is implemented in an open PR
Pending: 
- Rebase whenever the PR develop merges to next
