### ISSUE TITLE
[Signer] Update RunLoop to use stacks-sbtc FrostSigner directly

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#3913]
Instead of using the SigningRound in the RunLoop, use FrostSigner object directly. 

Depends on https://github.com/Trust-Machines/stacks-sbtc/issues/700

**Comment by xoloki** [comment]
We shouldn't do this.  All relevant code from `stacks-sbtc` is being moved into `wsts`: https://github.com/Trust-Machines/wsts/pull/22

If we want the `verify_msg` functionality it should go into `wsts::state_machine`.
