### ISSUE TITLE
[Signer] Determine VRF algorithm to be used to select a coordinator from a list of signers

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#3915]
Currently the signer is hardcoded to take the very first signer as the coordinator. however, it should be doing some sort of VRF to determine the signer. This may be per reward cycle? Perhaps per transaction? per block height? This ticket includes the design but implementation should be done as part of a separate ticket.

**Comment by jferrant** [comment]
This is low priority. Not scheduled for any time soon.

**Comment by jferrant** [comment]
See https://github.com/stacks-network/stacks-core/blob/33c64f600a31e7967b6d40a02a3fcacc27ccd4f9/stacks-signer/src/runloop.rs#L328

**Comment by 8marz8** [comment]
Could we use the consensus_hash fetched from SortitionDB as the alpha (private message) and the signer’s stacks_private_key for generating a VRFProof in calculate_coordinator?
The proof can then be hashed and converted to a number to select a public key from the list.

**Comment by 8marz8** [comment]
@jferrant found this relevant discussion from before: https://github.com/stacks-network/sbtc/discussions/335
It resolves my concern that we could just use the public keys.
For the additional data part, retrieving parent_vrf_proof, consensus_hash, sortition_hash or any final combination that we choose to use, requires db connections and I am wondering if it's okay for signers to make db connections, especially if it requires additional configs from them.

**Comment by 8marz8** [comment]
@AshtonStephens 
Yep, I think this can be closed as I created another issue for the follow up changes:
https://github.com/stacks-network/stacks-core/issues/4292
