### ISSUE TITLE
[StackerDB] update stackerdb StackerDBChunkAckData to return an error type and not just a reason string

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#3917]
To improve error handling in applications using stackerdb, make StackerDBChunkAckData return an error code and not just a reson string as it can be janky to match against strings.

**Comment by jcnelson** [comment]
Would a JSON structure work?  If you can provide the desired structure, I can make it so that the `reason` field contains it.

**Comment by jferrant** [comment]
I think a JSON structure works. It doesn't have to be this exact structure but something along these lines?
```JSON
{
  "error": {
    "code": "0",
    "message": "Invalid version number.",
    "description": "Data for this slot and version already exist."
}
```
If there are any other instances in stacks-blockchain code that return a JSON error struct, maybe we should try to be consistent with them?

**Comment by jcnelson** [comment]
This has been merged
