### ISSUE TITLE
Nokamoto[Block Proposal]: Signer binary handles BlockProposal event stored to StackerDB

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#3928]
To support the argon milestone, the signer binary must receive an event from the stacks-node when the current tenure's miner submits a block for the signers to approve.

The signer binary will need to do some processing on this block proposal, but the first step is to handle the event at all.

This requires registering for the correct StackerDB event, fetching the stored data, and deserializing it into a BlockProposal.

**Comment by saralab** [comment]
Related to **https://github.com/stacks-network/sbtc/issues/368**

**Comment by saralab** [comment]
Prereq:  Retrieve the winning miner from .miners contract

**Comment by kantai** [comment]
This requires figuring out who the current miner is -- this can be queried from the `.miners` contract using the RPC endpoint. This also is relayed in burnchain block events. I wouldn't say this is a pre-req, it's just a component of implementing this.
