### ISSUE TITLE
Nakamoto[Block Proposal]: Signer binary submits block proposal to stacks-node for validation

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#3929]
To validate a BlockProposal from the current tenure, the signer binary needs to:

1. Check that the block proposal was produced by the active miner.
2. Check that the block proposal's parent was the last block signed by the signer.
3. Submit the proposal to a `stacks-node` to validate the block for correctness.

Step 3 is handled via the block proposal endpoint (implemented in #3889)

**Comment by saralab** [comment]
Related to https://github.com/stacks-network/sbtc/issues/367
