### ISSUE TITLE
Nokamoto[Block Proposal]: Signer binary issues signature and broadcasts the block

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#3930]
After the signer binary has validated a block proposal, it needs to sign the block.

In the Neon milestone, this should be a simple "single signature".

Once the signature has been applied to the block, the signer binary passes the now-finished block back to the `stacks-node` for broadcasting to the rest of the network.

**### Copied from the sBTC breakdown:** 

Description
Update signers to perform signing rounds Nakamoto block stacker signature hash (the entire block header including miner signature but NOT including stacker signature)

Context
Signers are responsible for validating/signing Nakamoto blocks and returning them to the miner. This ticket enables us to perform the actual signing side of things.

Expected Approach
The message bytes being sent via the signing rounds need to include probably some message type to indicate what type of thing is being signed so that signers can deserialize the contents into a nakamoto block vs btc transaction to inspect. Signers should be able to decide whether they want to sign or not so being able to inspect the contents is required as part of this ticket.

Acceptance Criteria
 PR adds the feature to sign blocks
 PR adds an integration test for signing a Nakamoto block that includes both a failure case (no quorum), no, and yes result

**Comment by saralab** [comment]
Related to https://github.com/stacks-network/sbtc/issues/380
