### ISSUE TITLE
Nokamoto[Block Proposal]: Signer binary must produce TenureChange transaction

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#3932]
In addition to signing blocks, in Argon, the stacker signer binary is
responsible for creating `TenureChange` transactions. These transactions
should be issued whenever the signer's associated `stacks-node` processes
a new sortition. When a new sortition is processed, the signer should receive
an event, and then sign a new transaction declaring the new Tenure.

The tenure change transaction is composed of:

* The StacksBlockId of the last block from the previous miner that they processed.
* The number of blocks produced since the last non-empty sortition
* A flag to indicate which of the following triggered the tenure change
   - A valid winning block-commit
   - No winning block-commits
   - A “null miner” won the block-commit (in Neon, this won't be an option)
* The ECDSA public key hash of the next tenure's block-signing key
* The stacker-signer's signature over the transaction

**Comment by saralab** [comment]
@soju-drinker Closing this issue. Context: 
Miner can produce the `tenurechange` transaction and the block validation logic must ensure that we cover the edge scenarios
