### ISSUE TITLE
Nakamoto: New `TenureChange` Stacks transaction

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#3944]
In Nakamoto, each bitcoin block may perform a sortition -- much like the Stacks 2.0 protocol performs sortition. However, because the bitcoin commitment no longer contains the current stacks tip (see: #3892), the actual handoff from one miner to the next requires a `TenureChange` stacks transaction.

This is a new `TransactionPayload` variant which indicates that the prior tenure has ended (and what the last Nakamoto block of that tenure was) and that the next tenure should begin.

It should contain:

* The StacksBlockId of the last block from the previous tenure
* The number of blocks produced in the previous tenure
* A flag to indicate which of the following triggered the tenure change
      * A valid winning block-commit
      * No winning block-commits
      * A “null miner” won the block-commit (see the MEV solution below)
* The ECDSA public key hash of the current tenure
* A Schnorr signature from at least 70% of the Stackers
* A bitmap of which Stackers signed

Implementing this transaction payload for mockamoto involves:

1. adding the new transaction variant
2. adding a handler in `db/transactions.rs` which should verify that the current block is a Nakamoto block and that the `StacksBlockId` of the last block from the previous tenure is the current block's parent
3. adding a step in `NakamotoChainState` that checks for the presence of a `TenureChange` transaction, confirming that the current block was signed by the appropriate hash.

**Comment by jbencin** [comment]
I'm implementing `StacksMessageCodec` for `TenureChange` data... do we have a wire format defined for this already or can I just make something up?

**Comment by kantai** [comment]
Feel free to make something up -- but it should resemble other transaction wire formats (e.g., same endianness).
