### ISSUE TITLE
PoX-4.clar Draft

### ISSUE THREAD

**Issue by setzeus** [stacks-network/stacks-core#3948]
A goal for Sprint 6 from the ClarityWG (specifically @setzeus & @friedger) is to lay down a PoX-4 draft in src/chainstate/stacks/boot. This draft should result in answering a few open questions such as:

- [ ] What's needed from the signer group? (in coordination with @jferrant)
- [ ] What functions (if any) will persist from from the [sBTC-mini stacking pool](https://github.com/stacks-network/stacks-blockchain/issues/3877)? 
- [ ] What functions (if any) need to be extracted from [other sBTC-mini contracts](https://github.com/stacks-network/stacks-blockchain/issues/3878)?

**What's the success case here?**
The success case here is a PoX-4.clar contract draft is completed in a branch & sitting in a PR with lively a discussion regarding requirements / needed updates. The success case is not necessarily merging as much as it is:

- [ ] Further refining scope of PoX-4 alongside Nakamoto requirements
- [ ] Convergence on a draft for which we can begin creating rust tests similar to [pox_3_tests.rs](https://github.com/stacks-network/stacks-blockchain/blob/fe45e9157bbbbe690260b306039a1adae0e7a86d/src/chainstate/stacks/boot/pox_3_tests.rs)

**Comment by setzeus** [comment]
Summarizing my conversation with @jferrant yesterday it's clear that the Signer WG has a few requirements from the Clarity contract side. Two issues created & broken out as a result. 

Below are super short sentence-long descriptions of requirements stemming from these conversations:

**1. .sBTC must be a boot contract**
Wasn't currently planned or known. Likely doesn't change much or at all but still need to better understand effects of making this a boot contract.

**2. sBTC on-chain data requirement(s)**
As mentioned in #3958, signers need to know a few sBTC items previously held in sBTC-registry.clar such as pending peg-ins, pending peg-outs, handoffs, & whether DKG is stale.

**3. StackerDB contract requirements**
Unbeknownst to me previously, StackerDB is actually data held on a Clarity contract. It's very, very minimal data (essentially two lists of tuples {signer, slots}) but it's data we must account for - whether this means StackerDB is a boot contract or a normal contract with only write-permission from boot contracts is still up to debate  & discussed in #3957. 

**4. sBTC-registry open question**
The requirements gathered from these two conversations makes me heavily lean on the assumption that we might bring back the sBTC-registry contract previously written in sBTC-mini. Creating an issue to discuss.

**Comment by setzeus** [comment]
Considering adding Clarinet, *not* adding it to the CI & still add rusts tests like existing boot contract rust tests. Or create a separate runner?

**Comment by setzeus** [comment]
Not updated yet, a lot of other priorities.

**Comment by friedger** [comment]
pox-4 exists now in branch `next`.
There are more explicit issues now.
