### ISSUE TITLE
[Clarity] need helper function for whether DKG is set for the current reward cycle

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#3969]
DKG needs to be run once at the start of every reward cycle before signers can begin fulfilling their duties and for old signers to be able to initiate a wallet handoff. 

Add a helper function to the .pox-4 (or other appropriate contract) for signers to retrieve the DKG value for a given reward cycle.

Relates to : https://github.com/stacks-network/stacks-blockchain/issues/3948

**Comment by friedger** [comment]
Info is available in pox-4
