### ISSUE TITLE
[stacks-signer] coordinator should trigger DKG automatically as required

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#3971]
Update the code to check some endpoint/pox contract state to see if the DKG aggregate key has been set for the given reward cycle. If not, the coordinator should trigger a DKG round.

Relates to https://github.com/stacks-network/stacks-core/issues/3990
Depends on https://github.com/stacks-network/sbtc/issues/392

**Comment by saralab** [comment]
- Replay stacker db events to determine state [ revisit estimates] 
- Update stacks-signer to store local state between crashes - 1. enable 2. store
- Retrieve aggregate public key from stacks node  - RPC endpoint 
- Retrieve aggregate public key vote for a given signer key per cycle - 
- Add an end-point for to-do list for signers (run DKG, pending transaction, etc...)- 

@jferrant : Link the existing issues to these tasks

**Comment by jferrant** [comment]
This is not quite done actually. This should encompass also "If a coordinator goes down, some other coordinator takes over".
