### ISSUE TITLE
[clarity] Setup Standard Clarinet Project For PoX-4 Flow Tests

### ISSUE THREAD

**Issue by setzeus** [stacks-network/stacks-core#3976]
**Describe the bug**
In the previous sBTC-Mini work we had a clarinet project structure inside the repository that allowed us to build out a useful testing suite for testing PoX-4.

Before we can move forward on PoX-4 work in this repo, it's critical we can stand-up our Clarity/Clarinet/TypeScript test suite.

The success case for this issue would be a pseudo-port / minified-version of the setup previously found here: https://github.com/Trust-Machines/stacks-sbtc/tree/main/sbtc-mini

**Comment by setzeus** [comment]
Discussed in #3948 , currently blocked by repo testing considerations (adding Clarinet).

**Comment by setzeus** [comment]
No updates here or #3948 as we figure out how to best work with new repos

**Comment by friedger** [comment]
clarinet testing exists now in `contrib/core-contract-tests`

**Comment by friedger** [comment]
First implementation: https://github.com/stacks-network/stacks-core/pull/4100
Documentation still missing.

**Comment by friedger** [comment]
We are using clarunit now by Marvin https://github.com/stacks-network/stacks-core/issues/4203#issuecomment-1870391449
