### ISSUE TITLE
[stacks-signer] Stacks signer will infinitely loop if it fails to execute a command after resettting coordinator state

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#4013]
If a command fails to execute, it will attempt to reset the coordinator state and try again. However, this is put inside a loop and if it fails once (after reset), it will fail infinitely. 

See (Coordinator Reset):

https://github.com/stacks-network/stacks-blockchain/blob/5ac03fca4efef15c4992899266b1fec65e23a01a/stacks-signer/src/runloop.rs#L110
https://github.com/stacks-network/stacks-blockchain/blob/5ac03fca4efef15c4992899266b1fec65e23a01a/stacks-signer/src/runloop.rs#L84

See (Command Retry after Reset):

https://github.com/stacks-network/stacks-blockchain/blob/5ac03fca4efef15c4992899266b1fec65e23a01a/stacks-signer/src/runloop.rs#L123

TODO:
Fix the stacks signer to not loop forever if resetting the coordinator does not fix the problem. Most likely better to enter into an "Uninitialized state" to try to fix itself by reading contract/stacker db events for example.

**Comment by saralab** [comment]
Not needed
