### ISSUE TITLE
Nakamoto: Tenure Change transaction Validation

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#4014]
In order to support nakamoto in neon and beyond, the tenure change transaction must be validated further than in mockamoto.

* The block must be the first block in the miner's tenure. It cannot be in a subsequent block
* TenureChange must be for last_tenure + 1. No TenureChanges can be skipped.
* It must point to the last active miner's block-commit's StacksBlockId
* It must count up the number of blocks since the last block with a TenureChange (it may be zero; a block can have multiple TenureChange transactions per the design doc)
* It must be signed by the current Stacker set
* It must precede any other kinds of transactions (except coinbases?)

**Comment by jcnelson** [comment]
I'm already working on this as part of the coordinator PR, since I need to be able to generate Nakamoto block streams as part of the test infrastructure (`TestMiner`, `TestBurnchainBlock`, `TestPeer`).

**Comment by kantai** [comment]
Which of these are necessary for the coordinator PR?

**Comment by jcnelson** [comment]
Not all of them.  Just the ability to ensure that there is one `TenureChange` per tenure, and it's in the right place in the block stream.  I'm just trying to upgrade `TestPeer` to produce well-formed Nakamoto block-commits and block streams so I can verify that the coordinator will correctly detect the presence of and correctly handle new burnchain blocks and new Nakamoto blocks.  I'm focusing on getting `TestPeer` upgraded so I can switch over to implementing the network state machines.

**Comment by jcnelson** [comment]
I'll add a follow-on PR that performs all of the necessary validations.  I just wanted to point out that I'm already well-positioned to take this task, since I had to do a few of them already.

**Comment by saralab** [comment]
@jcnelson : To add more details on tasks needed for tenurechange validation
