### ISSUE TITLE
Nakamoto: pox-4

### ISSUE THREAD

**Issue by AshtonStephens** [stacks-network/stacks-core#4029]
This ticket is to design and implement the pox-4 contract that meets the definition defined in the in-progress SIP-025 https://github.com/stacksgov/sips/pull/155.

**Comment by jcnelson** [comment]
I'm working on this as part of my Nakamoto coordinator PR. I'll add the
stub pox-4 contents; I'm focused on booting it up for now.

**Comment by whoabuddy** [comment]
checking in as SIP-021 is now merged, can this be closed now?

**Comment by jcnelson** [comment]
Yes
