### ISSUE TITLE
[Nakamoto] Add pox-4 to `/v2/pox` RPC endpoint

### ISSUE THREAD

**Issue by zone117x** [stacks-network/stacks-core#4043]
I'm not sure if this is tracked or being implemented anywhere yet so opening an issue.

Clients have a critical dependency on this endpoint in order to determine how to construct stacking txs and other PoX related functionality. We need this available ASAP (e.g. in the mockamoto node) for meaningful progress pox-4 Stacking integration.

**Comment by jcnelson** [comment]
This is addressed in the fear/nakamoto-coordinator PR
