### ISSUE TITLE
[stacks-core] Update .pox-4 stacker registration functions to include a signer key

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#4057]
Currently there are two stacking fucntions: stack-stx and stack-aggregation-commit (I think) that should be updated to include a signer-key. This key should be tracked in a map of signer key to stacked amount for a given reward cycle.

**Comment by saralab** [comment]
Will be done in aggregate-commit & also necessary in stack-extend. 

When delegating provide a public key.

**Comment by setzeus** [comment]
Pasting design doc that mentions this issue for reference: https://docs.google.com/document/d/1IFTaHjEGHJkdFiEfKNayfmD0UlseoXpVcoMgJv0VW1g/edit?usp=sharing

**Comment by setzeus** [comment]
Closed / addressed by #4209
