### ISSUE TITLE
[stacks-core] Update the stacker-db contract from the list of registered signers

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#4058]
There should be a map of signer keys (public keys) to stacked stx in pox-4. Utilize this map to update the stacker-db config of the stacker-db instance to enable these signers to write to the appropriate slots. Note that we will need to sets of stacker-db slots. One for signers for cycle N, one for signers of cycle N+1.

**Comment by setzeus** [comment]
Pasting design doc that mentions this issue for reference: https://docs.google.com/document/d/1IFTaHjEGHJkdFiEfKNayfmD0UlseoXpVcoMgJv0VW1g/edit?usp=sharing

**Comment by setzeus** [comment]
Does #4125 change the requirements here?
