### ISSUE TITLE
[Nakamoto] Block downloader network state machine 

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-core#4063]
The Nakamoto node needs a new block-downloader state machine.  It will use the Nakamoto inventory vectors to identify blocks as available from peers, and download them in rarest-first order (as before).  New to Nakamoto, block requests are framed on a per-tenure basis -- a single fetch obtains the tenure's blocks.  In addition, there needs to be an endpoint to serve one of the last N tenures (for small N), and an endpoint for serving new blocks in the current tenure.

**Comment by saralab** [comment]
1: Adding get a tenures blocks , cursor system , streams blocks out of DB and makes available for nsw - S
2: separate endpoints - S
3: state machine : look at bitvectors, look at blocks for bad data etc - M

**Comment by saralab** [comment]
https://github.com/stacks-network/stacks-core/pull/4476
