### ISSUE TITLE
[Nakamoto] Initial block download network synchronization

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-core#4064]
When the Nakamoto node is booting up, its coordinator will need to be aware of the progress of network synchronization.  In particular, it should block the inventory vector state machine and the block downloader state machine from downloading blocks from reward cycles it has not yet processed, and from downloading blocks out-of-order.  The flow would be as follows:

1. coordinator processes the PoX anchor block for cycle N
2. coordinator processes all sortitions for cycle N
3. coordinator unblocks the inventory sync state machine so it can begin to query inventory vectors for reward cycle N
4. block downloader is awoken by the inventory sync state machine when it has new vectors for reward cycle N
5. block downloader fetches blocks _in order_ for reward cycle N
6. once a tenure has been downloaded and stored, the coordinator wakes up and processes it

**Comment by saralab** [comment]
This will be tackled in the block downloader state machine
