### ISSUE TITLE
[Nakamoto] Update pox_3_test.rs to pox4_test.rs

### ISSUE THREAD

**Issue by setzeus** [stacks-network/stacks-core#4088]
This issue is meant to mark the kickoff, not completion of the pox4_test.rs that'll be worked in parallel to pox-4.clar. Since pox-4.clar work is still in the early stages, the only confirmed changes worth implementing at the moment revolve around the data structures defined in the design document: 

https://docs.google.com/document/d/1IFTaHjEGHJkdFiEfKNayfmD0UlseoXpVcoMgJv0VW1g/edit#heading=h.tahn8ddco07r

**Comment by moodmosaic** [comment]
@jcnelson @kantai @setzeus 

In `pox_4_tests.rs` what should we use for the epoch and the activation height? In `pox_3_tests.rs` the latest one is 2.4

```rust
StacksEpoch {
    epoch_id: StacksEpochId::Epoch24,
    start_height: EMPTY_SORTITIONS + EPOCH_2_4_HEIGHT,
    end_height: STACKS_EPOCH_MAX,
    block_limit: ExecutionCost::max_value(),
    network_epoch: PEER_VERSION_EPOCH_2_4,
},

// ...

pox_constants.pox_3_activation_height = (EMPTY_SORTITIONS + EPOCH_2_4_HEIGHT + 1) as u32;
pox_constants.pox_4_activation_height = u32::MAX;
```

**Comment by moodmosaic** [comment]
@setzeus it turns out there's existing work on this done by @jbencin (see https://github.com/stacks-network/stacks-core/pull/4106). I reached out to Jeff this morning. Perhaps it makes sense to close this and have just one issue open, so we can have a single place to discuss.

**Comment by setzeus** [comment]
Copy, closing this as a duplicate @moodmosaic
