### ISSUE TITLE
Rustfmt action 

### ISSUE THREAD

**Issue by wileyj** [stacks-network/stacks-core#4099]
related to:
#4068
#4079

the way `rustfmt` is called in #4079 would need to be changed to allow for inputs for cmd line args. 
https://github.com/actions-rust-lang/rustfmt does not allow for this - but i think we can fork the repo (note to check license) to our composite actions repo: https://github.com/stacks-network/actions   and add in the changes we need. 

side effect is that we can open it up to other rust projects if it's done correctly. 

@jbencin

**Comment by wileyj** [comment]
#4168

**Comment by BowTiedDevOps** [comment]
Closed by https://github.com/stacks-network/stacks-core/pull/4478
