### ISSUE TITLE
Bitcoin Signet support in burnchain operations

### ISSUE THREAD

**Issue by wileyj** [stacks-network/stacks-core#4104]
Add support for the stacks-core blockchain to use bitcoin signet. 

details to be added later

**Comment by CharlieC3** [comment]
lol I'll close mine out

**Comment by diwakergupta** [comment]
Duplicates #4712 -- shall we close this @wileyj ?

**Comment by wileyj** [comment]
> Duplicates #4712 -- shall we close this @wileyj ?

sure! this issue adds nothing
