### ISSUE TITLE
Nakamoto: PoX-4 should have vote-disabling removed

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#4108]
PoX supports disabling PoX via voting. However, because of PoX-4's relationship to consensus in Nakamoto, the chain would stall (indefinitely) if a reward-cycle was vote-disabled. While the bar for vote-disabling PoX is pretty high, I don't think PoX-4 should support this (at least in its current form).

Removing this from PoX-4 (and the `boot/mod.rs` checks related to it) is a pretty straight-forward task and would also reduce the surface area for testing.

**Comment by friedger** [comment]
Fixed by #4163
