### ISSUE TITLE
[Nakamoto] Potential incorrect NakamotoCoinbase encoding

### ISSUE THREAD

**Issue by janniks** [stacks-network/stacks-core#4115]
**Describe the bug**
The code serializing the NakamotoCoinbase might be using unintended code paths.

The current `next` behavior for the NakamotoCoinbase encodes the vrf_proof as a length-prefixed byte vector. I believe it's intended to use a `u8, 80` (always 80 length).

The code should be using `consensus_serialize` directly. Instead it's using `write_next` on a vector, which obfuscates what's happening. (This can be fine in many cases, but in this case it hides that LP serialize is used, when the VRFProof actually has a `consensus_serialize`.

**Steps To Reproduce**
Hard for me to show in the Rust codebase, but the bytes used for the proof are more than needed. (due to LP)

**Code**

https://github.com/stacks-network/stacks-core/blob/53c168d6c1c4425c6c16a66b29dce4c2fe0ffb35/stackslib/src/chainstate/stacks/transaction.rs#L279-L297

https://github.com/stacks-network/stacks-core/blob/53c168d6c1c4425c6c16a66b29dce4c2fe0ffb35/stacks-common/src/types/chainstate.rs#L304-L313

https://github.com/stacks-network/stacks-core/blob/53c168d6c1c4425c6c16a66b29dce4c2fe0ffb35/stacks-common/src/codec/mod.rs#L186-L202

My recommendation here would be to try to use a top-level `consensus_serialize` as much as possible, reducing `write_next` calls / data transformations in the serialize cases.

---

Anyway, I could be wrong and this could be intended. If so, it might be worth adding a comment. But likely this could use a change, before it's consensus critical. 🍀

**Comment by jbencin** [comment]
Seems odd that we're using `.to_bytes().to_vec()` to serialize a `VRFProof` when it has `consensus_deserialize()` implemented. Made a small PR (#4121) fixing that, do you think that will fix your issue?

**Comment by janniks** [comment]
@jbencin Nice thanks, I think that should do it yeah 👍🏻

Good call @zone117x

**Comment by saralab** [comment]
This was merged as part of https://github.com/stacks-network/stacks-core/pull/4121
