### ISSUE TITLE
Two StackerDB instances needed due overlap in activity of old signer set and new signer set

### ISSUE THREAD

**Issue by MarvinJanssen** [stacks-network/stacks-core#4125]
During the end of the cycle there is a 100 block period where the old/current set of signers are still using StackerDB while the new set of signers is coming online and doing DKG through StackerDB. There therefore need to be two StackerDB instances, one where the old/current set of signers have write access and another where the next set of signers has write access.

@jcnelson suggested to have two instances and select the one to use based on whether the cycle is even or odd.

cc @jferrant

**Comment by setzeus** [comment]
Discussed During Clarity WG:

Using cycles vs. at-block
API should able to query for the latest stacker-db instance 
Only need this overlap of data for 100 blocks 
Need two instances

**Comment by MarvinJanssen** [comment]
I'm closing this because it was decided to revert to one StackerDB and assign slots to current and next signers in the same StackerDB. See also #4153.

**Comment by jcnelson** [comment]
Actually we need at least 2 stackerdbs (
https://github.com/stacks-network/stacks-core/pull/4153#issuecomment-1856097613).
We can throttle the write frequency based on whether or not we're in the
prepare phase, which addressed my main concern.
