### ISSUE TITLE
PoX-4 `revoke-delegate-stx` calls should fail if no state is changed

### ISSUE THREAD

**Issue by zone117x** [stacks-network/stacks-core#4146]
There's a discussion in PR https://github.com/stacks-network/stacks-core/pull/4094 around the behavior of `revoke-delegate-stx`. Right now the function always returns `(ok)` even if no state was changed:

https://github.com/stacks-network/stacks-core/blob/2c1c777b9ed0124a65e9cd2c019bd85f0735a5e0/stackslib/src/chainstate/stacks/boot/pox-4.clar#L636-L641

This means A) the new synthetic event for `revoke-delegate-stx` can be triggered repeatedly for no valid/useful reason, and B) the event has empty data: https://github.com/stacks-network/stacks-core/blob/789c23544e95058baa8610f3b928c238747e12a1/pox-locking/src/events.rs#L340-L346

Ideally the event would at least include the `delegate-to` address so that the event can be associated with the prior delegation. And ideally the call would return an error and not emit repeated events if called repeatedly.

**Comment by friedger** [comment]
Could you clarify the use case.
Revoking implies that the user does not delegate anymore after the tx was successful. 

Users have to check the stacking state nevertheless to learn about the stacking state.

**Comment by zone117x** [comment]
If an event observer receives a `revoke-delegate-stx` event with no data and possibly repeated, then it has to:
1. Scan through past `revoke-delegate-stx` events to ensure this is the first one that actually changed state as opposed to a redundant no-op event.
2. Scan through past delegation events to find the associated `delegate-to` address and stx amounts.

Why require event observers to handle more stacking state complexity when It seems trivial to improve this on the pox/stacks-node side?

**Comment by friedger** [comment]
Should `revoke-delegate-stx` fail if the delegation expired?

**Comment by friedger** [comment]
yes, it should fail.

**Comment by friedger** [comment]
fixed in #4157
