### ISSUE TITLE
Create a Controlled Testnet with 0.2[Neon Node] and the new Clarity Wasm

### ISSUE THREAD

**Issue by saralab** [stacks-network/stacks-core#4171]
This Testnet will : 
-  help us test the Nakamoto Consensus rules as part of the 0.2[Neon Node]. 
- Use the new Clarity Wasm VM 
- Run the API with support for the Nakamoto Tx Types: nakamoto coinbase, tenure change, tenure extension 
- Will have an Explorer with Nakamoto support 
- Have Stacks.js with the new tenurechange event support

**Comment by wileyj** [comment]
this is the "private testnet" that we've done in the past

**Comment by CharlieC3** [comment]
@wileyj I'll be using the config.toml [from this PR](https://github.com/hirosystems/stacks-regtest-env/pull/27/files#diff-fb3d4b1a12d753cadc68f990410547e128d2e51454efc6a2eb9d90318a8f8fd8) as a reference.

**Comment by CharlieC3** [comment]
Closing as this is complete as of last week.
