### ISSUE TITLE
Add delegate-stack-decrease

### ISSUE THREAD

**Issue by friedger** [stacks-network/stacks-core#4182]
**Is your feature request related to a problem? Please describe.**
The amount of Stack STX can be increased, but not decreased. As a stacker, I want to decrease the stacked amount. 

**Describe the solution you'd like**

* The function `delegate-stack-decrease` is added. Calling this function bookmarks the decrease amount for auto-unlock at the end of the cycle. At least 1 uSTX must be kept locked for the pool member. Calling `delegate-stx-increase` during the same cycle would change to bookmarked amount. An event `delegate-stx-decrease` is issued containing the amount and unlock height. 
* The function `stack-decrease` is **NOT** added. Instead solo stacking is removed to simplify the stacking protocol. See https://github.com/stacks-network/stacks-core/issues/4184 for details.

This has been added as a suggestion to the Nakamoto SIP: https://github.com/stacksgov/sips/pull/155#discussion_r1428764823

Update: Removing solo stacking has been moved to its own issue. 

**Describe alternatives you've considered**
Do not improve the stacking protocol

**Additional context**
Tool for Solo pools exist already: https://lockstacks.com/pool-admin?chain=mainnet

**Comment by jcnelson** [comment]
Copying my reply on the SIP here:

> The reason we didn't try to add a `-decrease` method for stacking and delegate-stacking is because it significantly complicates the auto-unlock logic. Without careful design it could introduce a DoS vector, whereby someone could stack and then decrease to 1 uSTX over many, many iterations in order to blow up the number of unlocks each node would have to process. Can you post a more detailed design proposal for `-decrease`?

**Comment by friedger** [comment]
I am not able to provide a design for -decrease
