### ISSUE TITLE
Remove solo stacking

### ISSUE THREAD

**Issue by friedger** [stacks-network/stacks-core#4184]
**Is your feature request related to a problem? Please describe.**
As a blockchain developer, many cases for solo and pooled stackers have to be considered. Solo stacking is used less and less often. Whales and institutional holders have adopted solo pools.

**Describe the solution you'd like**
The functions `stack-stx`, `stack-extend`, `stack-increase` are removed. Reasons: 1) With Nakamoto solo stacking will be much more involved, therefore running a stacking pool for a single user (solo pools) is not a big additional burden any more. 2) Currently, solo stacking is used less and less, solo pools have been adopted by whales and institutional holders.

This has been added as a suggestion to the Nakamoto SIP: https://github.com/stacksgov/sips/pull/155#discussion_r1428764823

The changes for removing solo stacking are small and reduce the number of cases for testing in pox-4.

**Describe alternatives you've considered**
Do not simplify the stacking protocol

**Additional context**
 Tool for Solo pools exist already: https://lockstacks.com/pool-admin?chain=mainnet

See https://github.com/stacks-network/stacks-core/issues/4182 for how removing solo stacking simplifies adding new features.

**Comment by jcnelson** [comment]
Hi @friedger, why do you believe this is necessary? This breaks backwards compatibility, and forces solo stackers to execute a more complex stacking setup.  If solo stackers want to switch over to one-person delegated stacking, they can already do so on their own schedule.

**Comment by friedger** [comment]
The main motivation was to simplify how to add `-decrease`. That is not given any more.

Other motivations are to increase test coverage and to remove a feature that is used less and less. I try to teach solo stackers to use solo pools for wallet hygiene (cold wallet vs hot wallet). 

Backwards compatibility is not given anyway because pox-4 is a new contract.

**Comment by friedger** [comment]
For now, this won't happen
