### ISSUE TITLE
Test Setup [common pox_4 catch-up]

### ISSUE THREAD

**Issue by setzeus** [stacks-network/stacks-core#4207]
Writing Rust tests for PoX-4 has made it clear that there are many steps required to properly setup a test to the point that it works with PoX-4 (such as advancing the chain until pox4 activation).

 There is therefore the opportunity to write out both a **base case** in addition to a few common helpers in addition to the ones already found in mod.rs (such as make_pox_4_lockup, make_pox_4_extend, get_reward_addresses_pox_4 etc...).

**Comment by MarvinJanssen** [comment]
Addressed in #4209.
