### ISSUE TITLE
"Increase fee" does not replace the existing transaction but create a new transaction

### ISSUE THREAD

**Issue by fyang1024** [stacks-network/stacks-core#4221]
## Describe the bug

I used Leather Wallet browser extension to submit a transaction. While the transaction is pending, I "increase fee" for the transaction in the wallet, but instead of replacing the existing transaction, it ended up with another transaction with duplicate nonce and finally got dropped after 256 blocks

The original transaction https://explorer.hiro.so/txid/0x297dc1eb1417afad7c95836c2f1136f8afcf38e83d677a9d9531f3d21384d215?chain=testnet

The replacing transaction
https://explorer.hiro.so/txid/0xdf2ff5d9d58fe5bf05ff0a559abbd35f56fda1d0d528181bbfa87e51c2d64323?chain=testnet 

## Steps To Reproduce

1. Interact with https://testnet.velar.co/ and submit 2 transactions with standard fee
2. Wait 30 seconds 
3. Increase fee 2x, 5x or 10x for the 1st pending transaction
4. Wait for the original 2 transactions to be confirmed and see the replacing transaction pending

## Expected behavior

The 1st transaction should be replaced and there should still be only 2 transactions after increasing fee for the 1st transaction

## Environment

 - OS: [e.g. Ubuntu / Debian]
 - Rust version
 - Output of `stacks-node version`

## Additional context

Please include any relevant stack traces, error messages and logs.

If you are encountering an issue with a smart contract, please include the smart contract code
that demonstrates the issue.

----

If you think this is eligible for a [bug bounty](https://testnet.blockstack.org/bounties), please check the relevant boxes below:

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [ ] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [ ] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [ ] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [ ] Resource exhaustion
- [ ] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

### Minor, Non-launch blocking bugs
**Minor bugs**
- [ ] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

**Comment by 314159265359879** [comment]
Thanks for reporting @fyang1024!

I believe this is currently working as intended atleast from the stacks-core perspective, I think what is not intended is that the wallet shows these "duplicate" transactions when they are not completely replaced on all nodes before one of them gets mined (that is what happens in the ideal situation). 

They are unprocessable transactions and should be classified as such by the API, wallets use to display the status of transactions. This could help resolve https://github.com/hirosystems/explorer/issues/1038 (API side), https://github.com/leather-wallet/extension/issues/1867 (wallet side)

And perhaps this discussion could mean other solutions entirely if it can be changed at the core: https://github.com/stacks-network/stacks-core/issues/4129

**Comment by fyang1024** [comment]
Thank you for the clarifications. I'll close this issue then since it's been worked on already
