### ISSUE TITLE
[pox-4] event name should be `delegated-to` or better `delegator`

### ISSUE THREAD

**Issue by friedger** [stacks-network/stacks-core#4246]
**Describe the bug**
In next branch, pox-4 emits an event for revoke-delegate-stx that contains data `delegate-to`.

**Steps To Reproduce**
Call revoke-delegate-stx

**Expected behavior**
The event should contain `delegated-to`

**Additional context**
@janniks suggested this change here: https://github.com/stacks-network/stacks-core/pull/4157/files/6445cd4a516e185dba33fba2606279e1a5d0ae12#r1452579328

**Comment by janniks** [comment]
No strong opinions. @friedger mentioned "I was inspired by the delegate-stx parameter name and the database column of the pox3_events table" -- that also makes sense to me, could also reuse if that's easier db-wise

**Comment by friedger** [comment]
the conversion from `delegate-to` to `delegated-to` happens in `delegate-stx` everything afterwards should be using `delegated-to`. This is also the name used in the return value of `delegate-stx`.

**Comment by friedger** [comment]
the api db would then use `delegator` I guess

**Comment by janniks** [comment]
👍 I'm fine with either, didn't see https://github.com/stacks-network/stacks-blockchain/blob/c77969b0a320a76ee3e85a37d8ba36914fd8f2b2/pox-locking/src/events.rs#L328 at first.

**Comment by friedger** [comment]
Then we should use `delegator` like here: https://github.com/stacks-network/stacks-core/blob/c77969b0a320a76ee3e85a37d8ba36914fd8f2b2/pox-locking/src/events.rs#L161

**Comment by janniks** [comment]
My bad, delegator doesn’t make sense, since we want the pool not the sender. The sender we always get I believe

**Comment by janniks** [comment]
Probably just best to keep as is. Revoke is semantically close to delegate so the same naming is fine, even if the response has a different variable name.

**Comment by friedger** [comment]
`delegator` is the pool.

**Comment by janniks** [comment]
Oh got it, 😅

**Comment by friedger** [comment]
Agreed to keep `delegate-to`
