### ISSUE TITLE
Signer should control which stackers can delegate to the signer 

### ISSUE THREAD

**Issue by friedger** [stacks-network/stacks-core#4247]
**Is your feature request related to a problem? Please describe.**
For legal or other reasons, signers might not want to accept signing duties for some stackers who want to delegate signing to them.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
@MarvinJanssen mentioned the issue first I think

**Comment by jcnelson** [comment]
Stacking transactions would require a signature over the stacking function's arguments from the signing private key.  The stacking function would authenticate the signature in order to validate the signing public key.

**Comment by kantai** [comment]
There's two possible ways to handle this:

1. Require a signature from the public key. The public key would sign something like a serialization of the `tx-sender` and the current reward cycle.

2. Require a public key allowance -- i.e., track which public key can be used by a `tx-sender` in a Clarity Map.

The advantage of (1) is that it simplifies the PoX contract. The advantage of (2) is that it doesn't require the signer to actually _use_ their signing key before the stacking cycle starts.

**Comment by jcnelson** [comment]
Another advantage of (1) is that you can change your key in the same transaction as you stack, so you don't have to worry about mempool congestion preventing you from rotating your signing key.

**Comment by hstove** [comment]
@saralab to assign me (hoping I can get added to the repo/org so I can add myself)

**Comment by diwakergupta** [comment]
> @saralab to assign me (hoping I can get added to the repo/org so I can add myself)

igotchu

**Comment by friedger** [comment]
Currently, Fast pool has implemented a self-service pool. This requirement will break the pool.

**Comment by friedger** [comment]
Currently, Fast pool accepts any stacker as pool member. It is a self-service pool.
With the requirement to provide a signature the pool's self-service feature will break.

**Comment by hstove** [comment]
@friedger yes, but you should be able to build tooling to automatically generate signatures for anyone who wants to join.

**Comment by hstove** [comment]
@MarvinJanssen, now that the signer key is only provided at `stack-aggregation-commit`, is this still really an issue? Stackers don't need the key or signature during their transactions, nor do pools need the key/sig for `delegate-stack-stx` etc. And because the signature is only needed on `stack-agg-commit`, it can be generated only occasionally and from a secure setup.

**Comment by MarvinJanssen** [comment]
That's true. It would only remain for solo stacking which is a specific use-case. Nonetheless, the problem would remain there.

**Comment by friedger** [comment]
How does this work for solo stackers stacking for 12 cycles? Which key do they need to use as the signing key changes every cycle?

**Comment by hstove** [comment]
@friedger I don't think you need to rotate your signer key every cycle anymore - it only changes with `-extend`.

**Comment by friedger** [comment]
If half of the stackers are solo stackers for 12 cycles and the other for 6. Then the first 6 cycles the aggregate public key is the same.
Thereafter, some stackers extend and the new key is created using the data from 6 cycles ago for the other stackers?
