### ISSUE TITLE
Stacker liveness enforcement in the stacks-node

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#4248]
The `stacks-node` will take the signer participation bit vectors as a given from the signer set (#4241), but it _does_ need to implement the punishment for non-participation. As discussed in the SIP, this should take the form of losing PoX rewards, but the exact design of this still needs to be designed and implemented.

Because it impacts a `block-commit`'s outputs, this means that `block-commit`s cannot be validated without the data that goes into the punishment (the prior stacks block's bit vectors).

**Comment by AshtonStephens** [comment]
Depends on info from discussion https://github.com/stacks-network/stacks-core/discussions/4195

**Comment by gofaraway002** [comment]
> Depends on info from discussion https://github.com/stacks-network/stacks-core/discussions/4195

**Comment by andrerserrano** [comment]
Hi team - what was the solution here? What are the exact penalties signers should expect (i.e. rewards will be halted after a signer is down for X blocks)?
