### ISSUE TITLE
[Nakamoto] Emit amount stacked for the subsequent cycle when the PoX anchor block is set

### ISSUE THREAD

**Issue by zone117x** [stacks-network/stacks-core#4255]
Related to signer support in the API & Explorer https://github.com/hirosystems/explorer/issues/1248

The API and Explorer need to know the total STX amount for PoX cycles. Ideally, this would be calculated and emitted when the PoX anchor block is set. Ideally it would be part of the existing `/new_block` payload which is currently the only event that doesn't have race-conditions / out-of-order threading issues.

**Comment by zone117x** [comment]
@kantai does this sound about right, and is it okay if I assign this to you?

**Comment by kantai** [comment]
Yeah -- that's fine. What you're looking for is basically the complete stacker set, right? This is event data that is needed by the signer binary anyways. I'm not sure that it'll be possible to include in `/new_block`, because the selection of the reward set doesn't occur during the processing of a block.

**Comment by zone117x** [comment]
> What you're looking for is basically the complete stacker set, right?

I think this issue is probably just for aggregate STX amount, and more complete data is covered by https://github.com/stacks-network/stacks-core/issues/4256 and https://github.com/stacks-network/stacks-core/issues/4257 -- does that make sense?

> I'm not sure that it'll be possible to include in /new_block

Ah okay, is there a way to ensure this new event doesn't have race-conditions against the `/new_block`? Almost all other events can come in out-of-order (in relation to each and/or `/new_block`) -- the API has different approaches to handle different events like A) complex detection and reconciliation code, B) presenting potentially inconsistent data to clients, C) dropping the event because it's too complex/expensive/damaging to do otherwise.
