### ISSUE TITLE
[Nakamoto] Emit signer performance data

### ISSUE THREAD

**Issue by zone117x** [stacks-network/stacks-core#4257]
Related to signer support in the API & Explorer https://github.com/hirosystems/explorer/issues/1248

The API and Explorer would like to show signer performance, e.g. a record of uptime and slot success rate.

It sounds like some changes in addition to the event emitter may be required:
> I think this requires an extension to the NakamotoBlock event: inclusion of which stackers signed off on the block. The FROST protocol doesn't actually make this recoverable, but stacks-core needs this in place anyways to punish non-responsive signers, so it should be easy to add once that's in place.

Note: this is probably a nice-to-have and lower priority compared to the other signer related events.

**Comment by saralab** [comment]
@AshtonStephens Can you drop in specific details here

**Comment by hstove** [comment]
I took a look at this today, and I'll admit I'm not quite sure where to start. I can figure out how to add data to the dispatched event, but I'm not sure where (or if) we store signer participation. @kantai any pointers?
