### ISSUE TITLE
[Clarity] Signer key represented as principal in stacker db contract

### ISSUE THREAD

**Issue by friedger** [stacks-network/stacks-core#4264]
The signer key is sometimes represented as `principal` (in stacker db) sometimes as buffer (in stack-stx).

The signer key should be represented with the same type.

**Comment by jcnelson** [comment]
Update to this after talking with @kantai -- I think PoX should take `(buff 33)` as an argument, but convert it to a `principal` when it stores the stacking state record.  So, the `signing-key` value would be a `principal` derived from the `(buff 33)` argument.  The reason for this is that the StackerDB system will treat the whole `.signers` contract as invalid if any of the slot signer principals is not a standard principal, and we don't want to risk that happening.

**Comment by MarvinJanssen** [comment]
This was addressed in #4263 and #4269.
