### ISSUE TITLE
[Nakamoto] Retrieve the signer config from the stacks node

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#4283]
The signers currently load their config information from a file (their signer id, the list of signer public keys and their corresponding key ids). Retrieve this info from the node either from an rpc endpoint call or via a contract call.

**Comment by 8marz8** [comment]
Is this related to #3912 ?
To clarify, should we completely eliminate loading from the config, or only retrieve fields available through the contract/node RPC? - meaning the Config remains but only some fields are loaded from the config and the rest are looked up via contract/rpc

**Comment by jferrant** [comment]
> @jferrant Is this related to #3912 ? To clarify, should we completely eliminate loading from the config, or only retrieve fields available through the contract/node RPC? - meaning the Config remains but only some fields are loaded from the config and the rest are looked up via contract/rpc

It is dependent on https://github.com/stacks-network/stacks-core/issues/4298
Once this ticket is done, you should have enough info to build the signer_id, signers  (public key mapping to list of key_ids)
