### ISSUE TITLE
[Nakamoto] Create an RPC endpoint to retrieve the list of signer public keys and their total number of reward slots (vote shares)

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#4298]
In order for signers to be configured, there needs to be an endpoint available to call to retrieve the list of registered signer public keys and their corresponding number of vote shares / reward slots (key_ids)

**Comment by xoloki** [comment]
> In order for signers to be configured, there needs to be an endpoint available to call to retrieve the list of registered signer public keys and their corresponding number of vote shares / reward slots (key_ids)

To be clear, we need the signers' actual key_ids, not just the number of them.

**Comment by jferrant** [comment]
> > In order for signers to be configured, there needs to be an endpoint available to call to retrieve the list of registered signer public keys and their corresponding number of vote shares / reward slots (key_ids)
> 
> To be clear, we need the signers' actual key_ids, not just the number of them.

It can just be the number. We would then create the key ids manually. I.e. if alice's key has 100 shares and is the first in the returned list, she becomes signer_id 0 with key ids 1 through 100
