### ISSUE TITLE
Alternating StackerDB signer slot details and implementation

### ISSUE THREAD

**Issue by MarvinJanssen** [stacks-network/stacks-core#4307]
From my understanding, the consensus on StackerDB/slot usage is as follows:

- The slots of the signer StackerDB are divided among the current signer set and the previous signer set.
- The slots that contain the current signer set alternates.

If that is correct, then we still need to do the following from what I can see:

- [ ] Decide how to alternate the slots and at which offset. (I remember we just do even/odd check on the reward cycle.)
- [ ] Alternate which slots we write to in `handle_signer_stackerdb_update` and make sure we don't overwrite the last set.
- [ ] Determine which slots contain the current signer set in the voting contract.
- [ ] Only allow aggregate public key votes by members of the current signer set.
- _And potentially other things._

**Comment by setzeus** [comment]
Just re-arranging assignee since it looks like #4323 is implementing this.
