### ISSUE TITLE
[StackerDB] support large DBs

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-core#4309]
Right now, StackerDBs are limited to 4096 slots due to (1) Clarity's maximum type's size and (2) the fact that the current replication protocol sends the entire DB's metadata to a peer when discovering newer chunks.

We can address (1) by updating the trait interface to be able to scan through an unbound number of (principal, num-slots) pairs.  The interface could look like the following:

```clarity
;; Get a page of up to 4096 (principal, num-slots) pairs.  `page` is the page number, and starts at 0.
;; Returns a non-empty list on success
;; Returns an error of `page` is too big (see `stackerdb-get-num-signer-slot-pages`)
(define-public (stackerdb-get-signer-slots (page uint)) (response (list 4096 { signer: principal, num-slots: uint }) uint))

;; Return the number of pages of (principal, num-slots) pairs for which `stackerdb-get-signer-slots` will have data.
;; Does not fail.
(define-public (stackerdb-get-num-signer-slot-pages) (response uint uint))
```

Then, the implementation could organize signer slot allocations as a data map:

```clarity
;; The signer pages themselves.
;; `stackerdb-get-signer-slots` returns a value from this table.
(define-map stackerdb-signer-pages
   ;; page number
   uint
   ;; page
   (list 4096 { signer: principal, num-slots: uint }))

;; The number of pages in `stackerdb-signer-pages`.
;; This is the maximum key value.
;; This is returned by `stackerdb-get-num-signer-slot-pages`.
(define-data-var stackerdb-num-signer-pages uint u0)
```

Problem (2) can be addressed by (a) making it possible to query a page of slot metadata (instead of the whole run), and (b) introducing a sparse metadata query protocol.  When a StackerDB replica boots up, it will query each page of each peer to get a copy of the pages.  When servicing the query, the remote peer will remember will remember the (local) timestamp at which the query was serviced so it can return only _changes_ to the metadata on subsequent queries.  Then, when the peer asks again for metadata, the remote peer will use the timestamp to fetch from the StackerDB replica only the metadata entries that have changed since the last query.  If the number of metadata entries is sparse enough, it will reply with this change-set instead of a full page of metadata.  Otherwise, it will reply with the full page (whichever message will be smaller).  The remote peer will again update its (local) timestamp at which it serviced the local peer's query, so that subsequent requests for metadata can similarly be serviced with a change-set.

**Comment by kantai** [comment]
@jcnelson -- can you assign this to me?

I can handle updating the `.signers` contract to match this interface and the necessary updates to the `.signers` maintenance routine in block assembly (i.e., the signer set calculation), and updating the `StackerDB` config fetching methods should be pretty straight-forward.

**Comment by kantai** [comment]
Specifically, I'd handle updating the StackerDB config interface -- you're still the best fit for the updates to StackerDB messaging protocol.

**Comment by jcnelson** [comment]
Sure; want to create a separate issue for part (1) and I'll update this to be part (2)?

**Comment by jcnelson** [comment]
Actually, no need to do this. Just use multiple small StackerDBs.
