### ISSUE TITLE
Update from Muneeb: Changes to Stacks Whitepaper

### ISSUE THREAD

**Issue by clairetopalian** [stacks-network/stacks-core#4310]

**Comment by clairetopalian** [comment]
@RickSebastiaan @cuevasm TBD if this should be a blog post, Twitter thread, or other format.

**Comment by cuevasm** [comment]
I think a Twitter thread from an engineer just outlining the changes would be good. Maybe Kenny can do it since he knows this all really well now @kenrogers - then just close by saying the links have been updated
