### ISSUE TITLE
Stacks node must process successful `.signers-voting` results

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#4354]
The `.signers-voting` contract emits an event every time a vote is cast, but the `stacks-node` needs to use this data for getting the actual aggregate public key.

This is the method that currently loads the aggregate public key:

https://github.com/stacks-network/stacks-core/blob/next/stackslib/src/chainstate/nakamoto/mod.rs#L1800

It would need to be updated to invoke something like

```clar
(get-approved-aggregate-key reward-cycle) -> (option (buff 33))
```

Where `get-approved-aggregate-key` is a read-only method of `.signers-voting`.

**Comment by obycode** [comment]
Resolved with #4360.
