### ISSUE TITLE
[Nakamoto] Add signer key authorizations to negate requirement of signatures

### ISSUE THREAD

**Issue by hstove** [stacks-network/stacks-core#4379]
We recently added a `signer-sig` parameter to `pox-4` transactions that include a `signer-key` as an argument. The purpose of that signature is to ensure that the signer has authorized the use of their signer key.

This new parameter is problematic to use in burn ops, because the total `OP_RETURN` payload is too long if the signer signature is included.

Instead, we should add the ability for signer key authorizations to happen out of band. If enabled, the `signer-sig` can be omitted from Stacking transactions.

**Comment by friedger** [comment]
Will there be a burn op tx for authorisation registration ?
