### ISSUE TITLE
[Chainstate] Sortition::get_canonical_stacks_block_id() does not produce the correct StacksBlockId

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-core#4399]
The method `get_canonical_stacks_block_id()` produces an invalid Stacks block ID, because it uses the _sortition_ consensus hash instead of the _canonical Stacks tip_ consensus hash.  Fortunately, this only affects some unit tests, and a single debug output in the chains coordinator.

**Comment by kantai** [comment]
Is this nakamoto-specific?

**Comment by jcnelson** [comment]
Yes, for mockamoto tests. It really needs to be fixed everywhere, but it's
not worthy of a hotfix since the only place it's called in prod is in a
debug statement.

**Comment by jcnelson** [comment]
I've already fixed it in the downloader API PR
