### ISSUE TITLE
When there is only 1 signer, `stacks-signer` crashes due to underflow in WSTS

### ISSUE THREAD

**Issue by hstove** [stacks-network/stacks-core#4415]
I caught an issue when running the Nakamoto devnet locally. I only have 1 signer, and in that case `threshold` is set to `0`, because 70% of 1 is 0 in integer terms. Same with `dkg_threshold`. This gets passed into WSTS, which generates a random number between 0 and `threshold - 1`, which is where the underflow happens.

I'll make an issue in WSTS, but adding here for visibility

- [code for setting `threshold` in `stacks-signer`](https://github.com/stacks-network/stacks-core/blob/9858d59ef87a14f9e2fde653b0ee1c4d3fe1aac6/stacks-signer/src/signer.rs#L158)
- [wsts underflow](https://github.com/Trust-Machines/wsts/blob/main/src/v2.rs#L80)

Question: we can update WSTS to not underflow, but should `threshold` be 0 when there is 1 signer? Any other consequences we should think about?

**Comment by xoloki** [comment]
The threshold is a function of the number of reward slots/key_ids, not the number of signers.  It's curious that a single signer would only have 1 reward slot.

What is the code that is doing the 70% calculation?  It likely should be rounding up not down.

`wsts` should probably panic if given a threshold of `0`, since it doesn't make any sense to continue at that point.

**Comment by hstove** [comment]
> The threshold is a function of the number of reward slots/key_ids, not the number of signers. It's curious that a single signer would only have 1 reward slot.

Yeah, I can't say whether this is "correct" or not, but I see 1 slot taken by my 1 signer. For example, here is the result of me fetching `/v2/stacker_set/$cycle` (see `weight = 1`):

```json
{"stacker_set":{"rewarded_addresses":[{"Standard":[{"version":26,"bytes":"ee9369fb719c0ba43ddf4d94638a970b84775f47"},"SerializeP2PKH"]}],"start_cycle_state":{"missed_reward_slots":[]},"signers":[{"signing_key":"03cd2cfdbd2ad9332828a7a13ef62cb999e063421c708e863a7ffed71fb61c88c9","stacked_amt":50160000000000,"weight":1}]}}
```

> What is the code that is doing the 70% calculation? It likely should be rounding up not down.

In the top post I linked to a spot in `stacks-signer`, but the code is

```rust
let threshold = num_keys * 7 / 10;
let dkg_threshold = num_keys * 9 / 10;
```

Also I know that in our Clarity code, the same "round down" math is done to determine when an aggregate key has been approved via enough votes.

**Comment by xoloki** [comment]
We should definitely fix both the `stacks-signer` and `clarity` code to round up in those calculations.

**Comment by hstove** [comment]
Closing because #4455 merged
