### ISSUE TITLE
Merge feat/clarity-wasm-next

### ISSUE THREAD

**Issue by hugocaillard** [stacks-network/stacks-core#4509]
We've been maintaining this branch for while, first for the clarinet compatibility and now for the clarity-wasm work.
Here's the PR: https://github.com/stacks-network/stacks-core/pull/4093. (And this one before https://github.com/stacks-network/stacks-core/pull/3293)

This branch is getting quite big and hard to maintain, I'd like to start a conversation regarding merging the work that is there.

### What does this branch do?

This branch is needed for two different purposes:
- Compatibility with Clarinet (ability to compile the clarity crate to Wasm) 
- Implement clarity-wasm (epoch gated, could be feature-flagged as well)

_This can be confusing, but **compiling the Clarity crate to Wasm** and **clarity-wasm** are to very different an unrdelated things. They happen to be on the same branch because Clarinet needs both._

#### Compatibility with Clarinet

Clarinet depends on the clarity vm (stacks-core/clarity), and needs to be compiled to Wasm. That's useful for the Clarinet JS SDK and the VSCode extension, and could unlock more possibilities in the future in order to analyze and execute clarity code directly in the browser (in developer tools).
It mostly mean feature flagging some part of the clarity-vm (see [diff in the cargo.toml file](https://github.com/stacks-network/stacks-core/pull/4093/files#diff-5c8fd5d05635d5a86aebc54aef3b6592312632853a87a44cbd7daa0b89bb3a4bR58-R63)) 

#### Implementing Clarity Wasm

It adds the dependency to clar2wasm in stackslib and executes clarity code with clar2wasm if epoch >= 3.0 ([relevant code](https://github.com/stacks-network/stacks-core/pull/4093/files#diff-501b6f12de26703f710ae663efd2063101529f361b1c2587c574737c29536d2cR1255-R1265))

### Why is it hard to maintain?

- It's difficult to keep the branch up to date with `next` because of frequent conflicts and complexity to merge next on to this branch
- It's easy to introduce changes on `next` that break the possibility to compile stacks-core/clarity to wasm (mostly because `next` is already not wasm friendly, so there's no check in CI) 

### Moving forward

The branch as it today is not in merge-able state but could easily be. We should agree and the best path

- Could it be ready for review as it is?
- Should we split into two PRs? One that enable the compilation to wasm and one that implement clarity-wasm?
- In the Cargo.toml files, most of the internal dependencies are targeting github (`stacks_common = { package = "stacks-common", git = "https://github.com/stacks-network/stacks-core.git", branch = "feat/clarity-wasm-next" }` instead of relative path (`stacks_common = { package = "stacks-common", path = "../stacks-common" }`), this is obviously something we would extract into an other branch and not merge. It'll be needed as long as the packages are not in a state ready to be published on crates.io.

**Comment by smcclellan** [comment]
@obycode @cylewitruk @csgui please review when you have a moment.

**Comment by obycode** [comment]
I think we should split it into two PRs as you described. I don't think we should merge any clarity-wasm specific code into next yet.

**Comment by obycode** [comment]
I think we can go ahead and close this @hugocaillard.
