### ISSUE TITLE
test: testnet with heavy mempool activity

### ISSUE THREAD

**Issue by obycode** [stacks-network/stacks-core#4538]
We need to bring up a testnet environment that has realistic block timings, and then pound it with lots of transactions of various types. It needs to be enough transactions that the miner cannot empty the mempool with one pass at building a block. Among other things, we'll want to pay attention to:
1 - Will the miner create reasonably-sized blocks at a reasonable pace?
2 - What happens when the block validation takes a significant amount of time (relative to the signer timeout and the block creation time)?

**Comment by hstove** [comment]
https://github.com/hirosystems/stacks-regtest-env/pull/35

**Comment by obycode** [comment]
That's awesome. Thanks @hstove! I think it would be interesting to also see how it does with a mempool full of all stx transfers (best-case for number of transactions).

**Comment by hstove** [comment]
I tweaked the "flood" script to support a higher amount of parallel accounts and then tested with 100 accounts keeping 5 chained transactions at a time. The first block of each tenure would max out the total execution cost of that tenure, and then no more transactions/blocks could be produced until the next tenure. I think that's basically expected in a full mempool environment, though there would be more transactions if it was just STX transfers

**Comment by obycode** [comment]
> The first block of each tenure would max out the total execution cost of that tenure, and then no more transactions/blocks could be produced until the next tenure.

Right, this is expected for now, but one of the improvements that is needed before 3.0. The miner should "ration" the space, and the signers should enforce this rationing.

**Comment by obycode** [comment]
> how do block and tenure dimensions compare in Nakamoto/3.0 to the maximum block dimensions of a Stacks 2.4 block

These haven't been set yet.

**Comment by hstove** [comment]
I'm going to close this given the new scripts in regtest-env, feel free to re-open if you think there's more to be done!
