### ISSUE TITLE
[pox-4] Stacking Stateful Tests

### ISSUE THREAD

**Issue by setzeus** [stacks-network/stacks-core#4548]
With the latest progress from @BowTiedRadone & @moodmosaic, it's now possible to test the core stacking functions in PoX-4 in a stateful manner. Starting with the core sequence for a solo stacker, a "complete" instance of stateful testing would cover *all* of the following state changes in a single run, across multiple reward cycles:

**Generating Authorization**
- [x] Signer explicitly creates an authorization

**Solo Stacking**
- [x] Solo stacking with a signature (stacks-stx)
- [x] Solo stacking with an authorization (stacks-stx)
- [x] Solo stacking extension with a signature (stack-extend)
- [x] Solo stacking extension with an authorization (stack-extend)
- [x] Solo stacking increase (stack-increase)

**Pool Stacking**
- [x] Pool delegating (delegate-stx)
- [x] Pool revoking (revoke-delegate-stx)
- [x] Pool stacking (delegate-stack-stx)
- [x] Pool stacking extended (delegate-stack-extend)
- [x] Pool stacking increased (delegate-stack-increase)
- [x] Allow contract caller (allow-contract-caller)
- [x] Disallow contract caller (disallow-contract-caller)
- [x] Pool aggregate commit with a signature (stack-aggregation-commit)
- [x] Pool aggregate commit with an authorization (stack-aggregation-commit)
- [x] Pool aggregate commit indexed with a signature (stack-aggregation-commit)
- [x] Pool aggregate commit indexed with an authorization (stack-aggregation-commit)
- [x] Pool aggregate increase (stack-aggregation-increase)

See also https://github.com/stacks-network/stacks-core/discussions/4433.

**Comment by moodmosaic** [comment]
Resolved via #4550 and #4725.
