### ISSUE TITLE
[pox-4] Remove Auto-Unlock

### ISSUE THREAD

**Issue by setzeus** [stacks-network/stacks-core#4565]
With signers auto-unlock becomes significantly more complicated to support. Consider removing the private function along with supporting functions / structs.

**Comment by zone117x** [comment]
For context, in pox-3 there have been 67 instances of an auto-unlocks. Attached is a csv of the events
[data-1710943918125.csv](https://github.com/stacks-network/stacks-core/files/14667868/data-1710943918125.csv)
