### ISSUE TITLE
Large amount of memory (~16GB) required to build next branch code

### ISSUE THREAD

**Issue by wileyj** [stacks-network/stacks-core#4584]
With the addition of LTO, the amount of memory required to build the next branch is quite higher than the current 2.4.0.1.0 release. 
Either this needs to be documented better in the readme, or there should be an option to disable LTO via feature flag. 

confirmed that next will build on the following:
- 64GB/12 cores
- 16GB/4 cores

and confirmed to fail building on anything with less than 16GB (it's *possible* 12GB may work, but i have no way to test that. i would expect it to build slower even if it did work).

when it fails, the system looks to be cpu bound via IOwait. if you let it run without intervention, the system *will* OOM on an 8GB machine:
```
Mar 23 16:45:55 ip-10-0-103-122 kernel: Out of memory: Killed process 18111 (rustc) total-vm:4310320kB, anon-rss:2935392kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:7308kB oom_score_adj:0
```

**Comment by jbencin** [comment]
I think what I'm going to do here is to create another profile that inherits `release`, maybe call it `release-opt`, and add the extra optimizations there, so they are not on by default

**Comment by jbencin** [comment]
On second thought, I think I'll leave the current `release` profile as-is and make a `release-lite` with `lto = "thin"`. I'll update the README to instruct users to try this if they have < 16 GB RAM or default profile OOMs
