### ISSUE TITLE
[Nakamoto] Stacks signer should store its DKG shares in StackerDB to enable disaster recovery

### ISSUE THREAD

**Issue by netrome** [stacks-network/stacks-core#4595]
In #4570, we introduced persistence for the signer to enable it to recover from restarts by storing their DKG shares in the signers own SignerDB. However, concerns were raised that in catastrophic scenarios the Signers may lose the contents of their SignerDB. Since DKG shares are connected to the liveliness of the chain, we want to take every measure possible to ensure the durability of these.

Therefore, it was proposed to have the signer encrypt their DKG shares and utilize StackerDB as a replicated durable storage for these.

### Definition of Done
A running signer can recover from a catastrophic restart (losing their SignerDB data in addition to all in-memory state), and continue signing blocks in the same signing round.

**Comment by wileyj** [comment]
>Therefore, it was proposed to have the signer encrypt their DKG shares and utilize SignerDB as a replicated durable storage for these.

reading through #4570 - i think you mean this as "...encrypt their DKG shares and utilize StackerDB..." correct?
my reading of that other PR is that it's being suggested to store a copy as a stackerdb object (encrypted with a private key)
is that correct?

**Comment by netrome** [comment]
> reading through #4570 - i think you mean this as "...encrypt their DKG shares and utilize StackerDB..." correct? my reading of that other PR is that it's being suggested to store a copy as a stackerdb object (encrypted with a private key) is that correct?

Yes, that's correct. Thank you for spotting this, I have updated the description.

**Comment by netrome** [comment]
An open design question is whether we'd like to **only** use StackerDB, or have the DKG shares stored in **both** StackerDB and SignerDB. The former will be simpler, though the latter would be even more resilient since there would not be a single system failure or bug which would cause signers to lose their DKG shares.

**Comment by jferrant** [comment]
> An open design question is whether we'd like to **only** use StackerDB, or have the DKG shares stored in **both** StackerDB and SignerDB. The former will be simpler, though the latter would be even more resilient since there would not be a single system failure or bug which would cause signers to lose their DKG shares.

I think we should have both, but make configurable? I think stackerdb was the default Jude wants. But maybe we could have the option to disable StackerDB and only use signerDB?

**Comment by netrome** [comment]
> I think we should have both, but make configurable? I think stackerdb was the default Jude wants. But maybe we could have the option to disable StackerDB and only use signerDB?

I like that idea. That both empowers signers giving them control over how to store their shares, while giving sensible defaults for those running the signers out of the box.

**Comment by wileyj** [comment]
@netrome @jferrant i like the idea here of having it configurable, but in the interest of time i would prioritize stackerdb as  default, then add in signerdb (with the option to save to either/or).

**Comment by netrome** [comment]
> @netrome @jferrant i like the idea here of having it configurable, but in the interest of time i would prioritize stackerdb as default, then add in signerdb (with the option to save to either/or).

Fair point. We already have the signerDB implementation though, but the extra complexity of adding the configuration option and testing all config combinations might not be worth the effort initially so yeah let's prioritize the StackerDB as a default initially.
