### ISSUE TITLE
Nakamoto: miner needs rules for selecting parent chain tip

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#4605]
The nakamoto miner must always build off of a chain tip that is the highest of:

1. The highest block in the miner's current tenure
2. The highest block in the current tenure's parent tenure

Where the current tenure's parent tenure is _the tenure start block committed to in the current tenure's associated block commit_.

This requires an update from the current logic:

https://github.com/stacks-network/stacks-core/blob/next/testnet/stacks-node/src/nakamoto_node/miner.rs#L663-L665

Which just queries the current canonical tip.

**Comment by jcnelson** [comment]
The miner has to build off of the highest processed tip in all cases, right?  But, wouldn't that always be the canonical chain tip?  In what circumstances is it not?

**Comment by kantai** [comment]
The issue is when the tenure immediately preceding the current miner doesn't produce a block until _after_ the current miner's block commit is submitted.

The current miner's block commit must be the first block of the parent tenure -- if they didn't receive a block from the preceding tenure, then they must assume the parent tenure is the preceding one to that, and that is where they must build.

Tenure A: Produces blocks `A_1...A_x`
Tenure B: Doesn't produce any blocks until Miner C has already produced and submitted block commit.
Tenure C: First block must descend from `A_x`, not `B_1`.
