### ISSUE TITLE
Manually Test High Level Signer Flow - Pool Stacker

### ISSUE THREAD

**Issue by AshtonStephens** [stacks-network/stacks-core#4617]
## Manually Test High Level Signer Flow - Pool Stacker

This ticket tracks the manual testing the pool Stacker on-boarding related actions.

The workflows under test should use the staging version of the lockstacks WebUI to make stacking related contract calls: https://staging.lockstacks.com

The following steps are a reduced list of checks from the workflow listed in the [PoX-4 testing document](https://docs.google.com/document/d/17-gF2hfI6Vle3MfcR1Mu42jzTyBX7uSeOEJDszxI0m4/edit).

- [x] Pool stacker can set pool delegate permission (`allow-contract-caller`)
- [x] Pool stacker can remove pool delegate permission (`revoke-contract-caller`)
- [x] Pool stacker can `delegate-stx`
- [x] Pool stacker can revoke delegate status (`revoke-delegate-stx`) 

--- 

#### Artifacts
- [x] Documentation of any bugs
- [x] Roughly recorded steps as they are relevant to bugs

**Comment by ASuciuX** [comment]
## `allow-contract-caller`
It only works for smart contracts, when delegating to another principal it calls directly delegate-stx

For smart contracts
![image](https://github.com/stacks-network/stacks-core/assets/151519329/7387e080-7f0b-4f8e-af44-c59201455c0a)


vs for principal
<img width="250" alt="Screenshot 2024-04-03 at 20 16 50" src="https://github.com/stacks-network/stacks-core/assets/151519329/89e9db0d-be1d-41d0-963c-4f82af7e7eaa">

**Comment by ASuciuX** [comment]
## `delegate-stx`
It happens by selecting this `custom pool` option and inserting the principal address or smart contract address to delegate to. A name and description to highlight the possibility of delegating to a principal as well will be useful.
![image](https://github.com/stacks-network/stacks-core/assets/151519329/a12e84db-0093-4864-afc7-90f8a39c3c79)


Tx where ST1C5EAGZ4PFVGJNK8ECEE82NW6NHHSTAG47D515V delegated 6,100,000 STX to ST1P6PNFM5CD12SWZF79DQ71A9WWB4PGPB20T69N3: https://explorer.hiro.so/txid/0x211b233e1a9872e54a56b3fa5cbfe05f9d4f6ad3f1b8f17f2f6f2dbd4d2b3b24?chain=testnet

**Comment by ASuciuX** [comment]
## `revoke-delegate-stx`

After calling `allow-contract-caller` and `delegate-stx` to a principal, there is the option to call `stop pooling` which is `revoke-delegate-stx`. It worked and can be seen here on [api](https://api.testnet.hiro.so/extended/v1/tx/0x8a69ba543fd1ff3f7d0163414443ac6e2608b28f8dc67473fb638e54538da61d).

**Comment by ASuciuX** [comment]
## Edge case on front-end

Context: The user is connected with account_1 from his wallet on lockstacks.com. The user changes the account selected to accounts_2 on the wallet, but lockstack displayed the same account_1 as connected. The user calls a function and it is called using the hiro account selected in the wallet, not in the application 
![image](https://github.com/stacks-network/stacks-core/assets/151519329/96c4da36-0ccd-4891-a5a4-e1ef6a06a394)
![image](https://github.com/stacks-network/stacks-core/assets/151519329/0dba96d9-aae1-4a31-9008-db3388a83bc1)

**Comment by ASuciuX** [comment]
TBD: add the other cases and scenarios for `2.Pool Stacker` https://github.com/stacks-network/stacks-core/discussions/4579

**Comment by ASuciuX** [comment]
- [ ] Pool stacker can set pool delegate permission (allow-contract-caller)
  - [ ] <s> Pool stacker cannot set permission on someone else’s behalf</s>
    not possible on frontend
- [ ] <s> Pool stacker can remove pool delegate permission (disallow-contract-caller) </s>
    not possible on frontend 
   <s>
  - [ ]  Pool stacker cannot remove permission on someone else’s behalf
  - [ ]  Revoke fails if stacker is not currently delegated
  - [ ]  Allowed contract cannot remove permission
  - [ ]  Other contract cannot remove permission
   </s>
- [ ]  Pool stacker can delegate-stx
  - [ ]  <s> Pool stacker cannot submit an invalid pox-addr-version </s>
   the frontend converts the bitcoin address to version and hash so no option to insert bad version
  - [ ]  Pool stacker cannot delegate to two pool operators at once
    case: 4 delegates to 5, cannot delegate to 6
  - [ ] <s> Allowed contract can delegate for the stacker </s>
  not possible on frontend as I am connecting with wallet, I am a principal, not a smart contract that is delegated to
  - [ ]  Other callers cannot delegate for the stacker
  case: 4 delegates to 5, 6 cannot call [delegate stack stx](https://staging.lockstacks.com/pool-admin?chain=testnet)
  - [ ]   <s> Other contract cannot delegate for the stacker </s>
  not possible on frontend as I am connecting with wallet, I am a principal, not a smart contract that is delegated to
- [ ]  Pool stacker can revoke delegate status (revoke-delegate-stx)
  - [ ] <s>  Pool stacker cannot revoke delegate status on behalf of anyone else </s>
  not possible on frontend 
  - [ ]  Pool stacker, if actively stacked, cannot revoke delegate status for the current reward cycle
   case: 4 delegates to 5, 5 calls delegate stack stx, 4 cannot call revoke delegate
  - [ ] <s> Allowed contract can revoke delegate status for the stacker </s>
  not possible on frontend as I am connecting with wallet, I am a principal, not a smart contract that is delegated to
  - [ ] <s> Other contract cannot revoke delegate status for the stacker </s>
  not possible on frontend as I am connecting with wallet, I am a principal, not a smart contract that is delegated to
