### ISSUE TITLE
Manually Test High Level Signer Flow - Pool Delegate 

### ISSUE THREAD

**Issue by AshtonStephens** [stacks-network/stacks-core#4618]
## Manually Test High Level Signer Flow - Pool Delegate 

This ticket tracks the manual testing the pool delegate on-boarding related actions.

The workflows under test should use the staging version of the lockstacks WebUI to make stacking related contract calls: https://staging.lockstacks.com

The following steps are a reduced list of checks from the workflow listed in the [PoX-4 testing document](https://docs.google.com/document/d/17-gF2hfI6Vle3MfcR1Mu42jzTyBX7uSeOEJDszxI0m4/edit).

- [x] Pool delegate can successfully provide a stacking lock for a pool stacker (delegate-stack-stx)
- [ ] Pool delegate can successfully delegate-stack-extend

> Note: We made a note that there may be other actions worth testing for pool delegation; we should update this ticket to include them so we know what we did.

--- 

#### Artifacts
- [ ] Documentation of any bugs
- [ ] Roughly recorded steps as they are relevant to bugs

**Comment by hstove** [comment]
I can confidently say that this has been manually tested many times on both testnet and mainnet. Closing!
