### ISSUE TITLE
Manually Test High Level Signer Flow - Signer Actions

### ISSUE THREAD

**Issue by AshtonStephens** [stacks-network/stacks-core#4619]
## Manually Test High Level Signer Flow - Signer Actions

This ticket tracks the manual testing the general Signer related actions.

The workflows under test should use the staging version of the lockstacks WebUI to make stacking related contract calls: https://staging.lockstacks.com

The following steps are a reduced list of checks from the workflow listed in the [PoX-4 testing document](https://docs.google.com/document/d/17-gF2hfI6Vle3MfcR1Mu42jzTyBX7uSeOEJDszxI0m4/edit).

- [x] Signer can vote for next cycle aggregate public key
- [x] Signer can add an authorization for a signer key

> Note: We made a note that there may be other actions worth testing for the general signer actinos; we should update this ticket to include them if we can.

---

#### Artifacts
- [x] Documentation of any bugs
- [x] Roughly recorded steps as they are relevant to bugs

**Comment by ASuciuX** [comment]
Linked to overall issue tracker https://github.com/stacks-network/stacks-core/discussions/4579

All flows that we are tracking for the frontend end user testing
- [ ] Signer can vote for next cycle aggregate public key
  - [ ] Signer cannot submit an existing aggregate public key
  - [ ] Signer cannot submit a public key shorter/longer than 33-bytes
  - [ ] Siger cannot vote twice in the same round
  - [ ] Signer cannot vote on behalf of another signer
  - [ ] Signer cannot vote without a signer-index
  - [ ] On a non-consensus reaching vote (<70%), X message is printed
  - [ ] On a successful consensus reaching vote (>70%), Y message is printed
- [ ] Signer can add an authorization for a signer key
  - [ ] Signer cannot submit a key not tied to their Stacks principal
  - [ ] Signer cannot submit a reward-cycle in the past (?)
  - [ ] Signer cannot submit a period longer than X/12?

**Comment by ASuciuX** [comment]
No bugs reported
