### ISSUE TITLE
cargo target features not being applied correctly when cross-compiling

### ISSUE THREAD

**Issue by wileyj** [stacks-network/stacks-core#4638]
when trying to build for arm64 on an x64 cpu using something like this (this is the build for macos-arm64, but is applicable for any arm64 build):
```
STACKS_NODE_VERSION="No Version Info"
GIT_BRANCH='No Branch Info'
GIT_COMMIT='No Commit Info'
BUILD_DIR=/build
TARGET=aarch64-unknown-linux-gnu

apt-get update && apt-get install -y git gcc-aarch64-linux-gnu libclang-dev llvm
git clone --single-branch https://github.com/stacks-network/stacks-core -b next ${BUILD_DIR}
cd ${BUILD_DIR}
rustup target add ${TARGET}

echo "RUSTFLAGS: ${RUSTFLAGS}"

CC=aarch64-linux-gnu-gcc \
CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc \
CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc \
cargo build --features monitoring_prom,slog_json,portable --release --workspace --target ${TARGET}
```

this is the resulting output:
```
...
'+fxsr' is not a recognized feature for this target (ignoring feature)
'-avx512dq' is not a recognized feature for this target (ignoring feature)
'-sse4a' is not a recognized feature for this target (ignoring feature)
'goldmont' is not a recognized processor for this target (ignoring processor)
^C  Building [=>                        ] 54/480: memchr, libc, ahash, futures-channel, rustc_version, syn, aho-corasick, syn, rustix(build.rs), quote, memchr, cc, standback(build), proc-macro2, ryu, tracing-core, typenum, hashbrown, regex-syntax, libc           
```

in .cargo/config, there was a change that allowed this work:
https://github.com/stacks-network/stacks-core/pull/4489/files#diff-f6009bd0d260464389ace37ab2f89adae993e1fa4a47f779e4c9859937005cedR10

but this was changed in https://github.com/stacks-network/stacks-core/commit/8ff05eb946f82b220aa6b78eb1c654e22295e353

the current directive *should* work, but it's clearly not being applied. confirmed that revertnig the change suppresses the warnings. 

becuase of this, the output of some builds is incredibly noisy - but the only build that will fail outright (for stacks-signer) is the cross-compiled macos-arm64 build

**Comment by zone117x** [comment]
From the slack chat:

Cargo feature flags cannot be used to toggling specific rustflags within .cargo/config. From the docs:
https://doc.rust-lang.org/cargo/reference/config.html
> cfg values come from those built-in to the compiler (run rustc --print=cfg to view), values set by build scripts, and extra --cfg flags passed to rustc (such as those defined in RUSTFLAGS). Do not try to match on debug_assertions or Cargo features like feature="foo".

It looks like we have to remove this from that config file, and specify it as an env var during the cargo build command.

**Comment by wileyj** [comment]
interesting. i can test this out - my use case here is literally for the release builds, so i can test that aspect pretty easily with the line removed from cargo/config

**Comment by wileyj** [comment]
> From the slack chat:
> 
> Cargo feature flags cannot be used to toggle rustflags within .cargo/config. From the docs: https://doc.rust-lang.org/cargo/reference/config.html
> 
> > cfg values come from those built-in to the compiler (run rustc --print=cfg to view), values set by build scripts, and extra --cfg flags passed to rustc (such as those defined in RUSTFLAGS). Do not try to match on debug_assertions or Cargo features like feature="foo".
> 
> It looks like we have to remove `RUSTFLAGS` from that config file, and specify it as an env var during the cargo build command.

@jbencin 

confirmed that something like this does work, where we set RUSTFLAGS for x64 builds only:

```
git clone --single-branch https://github.com/stacks-network/stacks-core -b next ${BUILD_DIR}
cat <<EOF> ${BUILD_DIR}/.cargo/config
[alias]
stacks-node = "run --package stacks-node --"
fmt-stacks = "fmt -- --config group_imports=StdExternalCrate,imports_granularity=Module"
EOF
```

ex of glibc-x64:
```
STACKS_NODE_VERSION="No Version Info"
GIT_BRANCH='No Branch Info'
GIT_COMMIT='No Commit Info'
BUILD_DIR=/build
TARGET=x86_64-unknown-linux-gnu
# Allow us to override the default `--target-cpu` for the given target triplet
TARGET_CPU=x86-64-v3
RUSTFLAGS="${TARGET_CPU:+${RUSTFLAGS} -Ctarget-cpu=${TARGET_CPU}}"



apt-get update && apt-get install -y git libclang-dev llvm git vim
git clone --single-branch https://github.com/stacks-network/stacks-core -b next ${BUILD_DIR}
cat <<EOF> ${BUILD_DIR}/.cargo/config
[alias]
stacks-node = "run --package stacks-node --"
fmt-stacks = "fmt -- --config group_imports=StdExternalCrate,imports_granularity=Module"
EOF

# all the build steps in ramdisk in an attempt to speed things up
cd ${BUILD_DIR} \
    && rustup target add ${TARGET} \
    && cargo build --features monitoring_prom,slog_json,portable --release --workspace --target ${TARGET}

```

and glibc-arm64:
```
STACKS_NODE_VERSION="No Version Info"
GIT_BRANCH='No Branch Info'
GIT_COMMIT='No Commit Info'
BUILD_DIR=/build
TARGET=aarch64-unknown-linux-gnu

apt-get update && apt-get install -y git gcc-aarch64-linux-gnu libclang-dev llvm git vim
git clone --single-branch https://github.com/stacks-network/stacks-core -b next ${BUILD_DIR}
cat <<EOF> ${BUILD_DIR}/.cargo/config
[alias]
stacks-node = "run --package stacks-node --"
fmt-stacks = "fmt -- --config group_imports=StdExternalCrate,imports_granularity=Module"
EOF

cd ${BUILD_DIR} \
    && rustup target add ${TARGET} \
    && CC=aarch64-linux-gnu-gcc \
    CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc \
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc \
    cargo build --features monitoring_prom,slog_json,portable --release --workspace --target ${TARGET}

```

using this change to `.cargo/config` combined with the RUSTFLAGS for x64 cpus (which is native to where the binaries are being built) allows us to build all binaries

**Comment by zone117x** [comment]
Should I open a PR with the changes to remove this from the cargo/config file? For now, I have had to just delete that file before building in order to avoid depending on a fork https://github.com/hirosystems/stacks-regtest-env/pull/26/commits/1360a17b25deae0785918c14ab06203438670099

**Comment by jbencin** [comment]
> Should I open a PR with the changes to remove this from the cargo/config file?

I think it's better if I open a PR to remove the `portable` flag and the `[target.'cfg(not(feature = "portable"))']` section. Since this is not technically allowed, it shouldn't be in our config file to begin with

Maybe there's a better way to do this, but for now I can add a note about setting `RUSTFLAGS` in the README

**Comment by wileyj** [comment]
> > Should I open a PR with the changes to remove this from the cargo/config file?
> 
> I think it's better if I open a PR to remove the `portable` flag and the `[target.'cfg(not(feature = "portable"))']` section. Since this is not technically allowed, it shouldn't be in our config file to begin with
> 
> Maybe there's a better way to do this, but for now I can add a note about setting `RUSTFLAGS` in the README

is it simple removing any mention of "portable"? i or matt can take care of that

**Comment by wileyj** [comment]
https://github.com/stacks-network/stacks-core/commit/b12aea34648c3c608945866ff86d6270cb48830e ?

**Comment by jbencin** [comment]
> https://github.com/stacks-network/stacks-core/commit/b12aea34648c3c608945866ff86d6270cb48830e ?

Basically, yeah

Also I think we should leave this in the `.cargo/config` file:

```toml
# Uncomment to improve performance slightly, at the cost of portability
# Note that native binaries may not run on CPUs that are different from the build machine
[build]
#rustflags = ["-Ctarget-cpu=native"]
```

And add a note about it in the README

**Comment by wileyj** [comment]
> > [b12aea3](https://github.com/stacks-network/stacks-core/commit/b12aea34648c3c608945866ff86d6270cb48830e) ?
> 
> Basically, yeah
> 
> Also I think we should leave this in the `.cargo/config` file:
> 
> ```toml
> # Uncomment to improve performance slightly, at the cost of portability
> # Note that native binaries may not run on CPUs that are different from the build machine
> [build]
> #rustflags = ["-Ctarget-cpu=native"]
> ```
> 
> And add a note about it in the README

ok - will do the needful
