### ISSUE TITLE
[pox-4] minor: delegate-stx doesn't validate hashbytes

### ISSUE THREAD

**Issue by janniks** [stacks-network/stacks-core#4645]
`minor`

In pox-4: `delegate-stx` validates the arg `pox-addr` `.version`, but it doesn't validate `.hashbytes`

I don't think this is a problem -- It should only happen via user error, and I don't think it can lead to any unexpected behavior, since the pool can only `delegate-stack-stx` (which validates `.hashbytes`) with the same `pox-addr` (aka checks for equality to delegation-state `pox-addr`) -- But happy for someone else to think it through as well, if this is not intended.

https://github.com/stacks-network/stacks-core/blob/19a373f89a4c82c4a82e75387416190bf5e61fce/stackslib/src/chainstate/stacks/boot/pox-4.clar#L661-L666

**Comment by kantai** [comment]
Yeah, I agree with your assessment, @janniks: I don't think this is a problem, because the pox-addr's hashbytes are checked in `delegate-stack-*` anyways.

**Comment by friedger** [comment]
Then the version check could be removed for improved performance.
