### ISSUE TITLE
[Nakamoto] Ensure that the stackerdb configurations for each signer contract is sensible

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#4647]
Currently it appears that a signer StackerDBConfig is initialized with the values listed in https://github.com/stacks-network/stacks-core/blob/8d4da579d301988997ab359404f9024b7561547b/stackslib/src/chainstate/stacks/boot/signers.clar#L5 or via the StackerDBConfig::noop which sets everything to max which is extreme.

See how the StackerDBConfig is initialized for a Miner and perhaps emulate something similar. I think our current write size limit according to the contract is 2 MB. However, I am not sure this is actually loaded into the StackerDBConfig in the node...I think it uses the u64::Max...Should be reduced to the 2 MB probably? (and the corresponding read by the stacks-signer should be limited to this same max.)

**Comment by hstove** [comment]
@jferrant we decided that this is a noop because `CHUNK_SIZE` is already smaller than `MAX_PAYLOAD_LEN`, right? If so, are we good to close?

**Comment by jferrant** [comment]
> @jferrant we decided that this is a noop because `CHUNK_SIZE` is already smaller than `MAX_PAYLOAD_LEN`, right? If so, are we good to close?

Yep! Will close now!
