### ISSUE TITLE
Two consistently failing tests

### ISSUE THREAD

**Issue by wileyj** [stacks-network/stacks-core#4686]
`tests::epoch_25::microblocks_disabled`
ex: https://github.com/stacks-network/stacks-core/actions/runs/8697187198/job/23853713055

`tests::nakamoto_integrations::follower_bootup`
ex: https://github.com/stacks-network/stacks-core/actions/runs/8697187198/job/23853716183

These tests are consistently timing out, suggesting they're waiting for something to happen that never does when executed as a github action.

**Comment by obycode** [comment]
These have been resolved!
