### ISSUE TITLE
Remove logging of `PeerNotConnected` to private/internal IPs

### ISSUE THREAD

**Issue by hstove** [stacks-network/stacks-core#4701]
Non-critical issue, but I've heard this recommended by others running a node, so I'm making a note of it.

When running a Stacks node, there are a lot of logs like `Failed to begin session with ...` or `Failed to connect to ...` with IPs in the RFC 1918 range (usually 10.0...). To help clean up logs and reduce confusion around error logs, it might be good to remove those logs if the IP falls in the private IP range.

**Comment by obycode** [comment]
Sorry if I'm forgetting the discussion around this, but is this just hiding the real problem? Why is it trying and failing to connect with those local addresses in the first place?
