### ISSUE TITLE
Nakamoto Miner[3.0] - Fix the 2 blocks dead time between 2.5 -> 3.0 transition

### ISSUE THREAD

**Issue by saralab** [stacks-network/stacks-core#4710]
In the current 2.5 -> 3.0 transition, when the 3.0 block height is reached the `Ne` miner tears down and the Naka miner starts up. This leads to a 2 block dead time. 

- `Ne` miner tears down a block early at the 3.0 transition height
-  Naka miner spins up 
-  Naka miner submits VRF key registration that needs to be accepted to next block 

Fix: 
- Solution for this involves Ne submitting a VRF key registration formatted for 3.0 during 2.5 [2.5.X release] 
- Miners should update to this ahead of the 3.0 release

**Comment by jbencin** [comment]
#4883 has been merged and brings this down to 1 block of dead time. Not sure if we can remove the final block, but @kantai has an idea
