### ISSUE TITLE
Signer Logs: Not Registered for Next Cycle

### ISSUE THREAD

**Issue by BowTiedDevOps** [stacks-network/stacks-core#4713]
The signer logs are a little bit misleading, they specify the signer is not registered for the next cycle, when the aggregation commit call is completed. This might just create confusion among others, as it did to me. Since the signer set is calculated at the beginning of the prepare phase (which still is cycle 83, with 100 blocks left until 84), the signer can't know that it will be registered, and for the reward phase in cycle 83 it prints this message:
```
INFO [1713987223.557146] [stacks-signer/src/runloop.rs:369] [signer_runloop] Signer is not registered for the current reward cycle (83) or next reward cycle (84). Waiting for confirmed registration...
```
Perhaps this can be changed to only print the reward cycle message if the prepare phase started, or just don't print it at all.

**Comment by friedger** [comment]
Maybe show the amount of locked stx in that message.
