### ISSUE TITLE
stack-extend can not be called with a period > 11

### ISSUE THREAD

**Issue by hugocaillard** [stacks-network/stacks-core#4722]
**Describe the bug**

`stack-extend` should be callable with a duration >= 1 and <= 12.
If a duration of 12 is passed, the error is triggered `ERR_STACKING_INVALID_LOCK_PERIOD` here: https://github.com/stacks-network/stacks-core/blob/878e17d3de3ac9625dda7005b874495a1667f7aa/stackslib/src/chainstate/stacks/boot/pox-4.clar#L520-L521.

There is a unit test the covers that and should be updated for pox-5
https://github.com/stacks-network/stacks-core/pull/4698/files#diff-67bd8d74c316858ceb9051995b07c2f189ff7c4121d6cb2cf5f44c95db58dfc2R706-R730

**Comment by jcnelson** [comment]
That is the correct behavior.  You cannot extend past 11 additional cycles,
because there cannot be more than 12 reward cycle entries for your PoX
address while you're stacked (including the one you're in right now)

**Comment by hugocaillard** [comment]
Ok thanks for clarifying @jcnelson, I wasn't sure. Thanks
