### ISSUE TITLE
Signer error: Could not lookup current miner while in active reward cycle

### ISSUE THREAD

**Issue by aryzing** [stacks-network/stacks-core#4760]
**Describe the bug**
Not sure if a bug, although I couldn't find any docs regarding this specific error. However, when running a node + signer, the signer is logging these error messages,

```
ERRO [1715155367.178493] [stacks-signer/src/signer.rs:194] [signer_runloop] Signer #6: Could not lookup current miner while in active reward cycle
```

**Steps To Reproduce**
Running a node + signer with default settings as recommended by the docs. Happens with both a kubernetes setup + when running both as binaries on the same host.

**Expected behavior**
No errors?

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Rust version: not installed
 - Version of the appropriate binary / software package

Versions,

```
INFO [1715177953.492234] [testnet/stacks-node/src/main.rs:293] [main] stacks-node 2.5.0.0.3 (release/2.5.0.0.0:52d425d, release build, linux [x86_64])
stacks-node 2.5.0.0.3 (release/2.5.0.0.0:52d425d, release build, linux [x86_64])

stacks-signer 0.0.1
```

**Comment by diwakergupta** [comment]
Duplicates #4757

**Comment by hstove** [comment]
PR is here: https://github.com/stacks-network/stacks-core/pull/4768
