### ISSUE TITLE
Nakamoto Signer[3.0] -  The sign_coordinator must be updated to send a block proposal message rather than initiate a signing round

### ISSUE THREAD

**Issue by saralab** [stacks-network/stacks-core#4775]
stacks-node: nakamoto_node::sign_coordinator

The sign_coordinator must be updated to send a block proposal message rather than initiate a signing round (with a NonceRequest). It will listen on the stackerdb for signer responses, as it does currently, but the signer responses will be `MessageSignature`s, rather than WSTS packets.

The sign_coordinator will need to validate the signatures and tally the results. Once the validation threshold is reached, they can announce the block.

**Comment by hstove** [comment]
NB: The function `begin_sign_v0` was added in #4781 , and the work for this ticket can continue in that code:

https://github.com/stacks-network/stacks-core/blob/d14e5b402b41d4524a70c0a1fe6e147551610109/testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs#L656
