### ISSUE TITLE
Update Nakamoto downloader to utilize signatures vec instead of aggregate public key

### ISSUE THREAD

**Issue by hstove** [stacks-network/stacks-core#4793]
In 3.0, blocks are verified by verifying a list of signatures against that block's reward set. Currently, the network downloader assumes an aggregate key is required and uses that to verify the block.

This task essentially means two things:

- [ ] Remove the need for a mandatory aggregate key in various places in the downloader
- [ ] Pre-load the reward set in the network state machine and use that to verify blocks

**Comment by jcnelson** [comment]
This has bee merged in #4817
