### ISSUE TITLE
Update unit test signer to use signatures instead of aggregate public key

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-core#4796]
The unit tests in the Stacks blockchain repo continue to expect the signers to produce and vote for an aggregate public key.  This needs to be changed in order for progress on other issues like #4793 to be made, since without these changes, it's impossible to test other PRs to fix other issues in this vein.

This issue is, in turn, blocked by #4781.

**Comment by hstove** [comment]
Closing as fixed in #4781 (and other related PRs)
