### ISSUE TITLE
Haruko Announcement

### ISSUE THREAD

**Issue by clairetopalian** [stacks-network/stacks-core#4825]

**Comment by clairetopalian** [comment]
https://docs.google.com/document/d/1BUjUMVRZoJVd6hfCuPFmNf8qulXoAXgE2a8MSYhfgoU/edit

**Comment by jcnelson** [comment]
I don't think this is the right place for this

**Comment by clairetopalian** [comment]
My apologies, this was an error - clicked the wrong project.
