### ISSUE TITLE
Signer voting mechanism and instructions for SIP-025

### ISSUE THREAD

**Issue by saralab** [stacks-network/stacks-core#4899]
- Add a command to signer binary to vote for SIP-025 
- Include instructions on "How to sign"

**Comment by jferrant** [comment]
Is the command in the signer meant to be a generic, sign this blob of bytes? Or is it meant to be "sign-yes" vs "sign-no" command which takes only a private key as an argument that internally constructs a very specific clarity struct with either a "vote: yes" or "vote: no" sort of syntax that then gets signed?  Some further detail would be helpful here.
