### ISSUE TITLE
Intermittent slow RPC performance

### ISSUE THREAD

**Issue by CharlieC3** [stacks-network/stacks-core#4933]
**Describe the bug**
When running `2.5.0.0.4`, the RPC server takes longer than expected to respond to HTTP GET requests. This seems to affect any endpoint (including simple ones like `/v2/info`).
![Screenshot 2024-06-28 at 10 21 38 AM](https://github.com/stacks-network/stacks-core/assets/2747302/325775e6-41b2-4055-8af4-a55179ba5126)

During times when this issue is observed, the response times for these endpoints can be over 10 seconds long, however most requests are still served quickly.

Additionally, it seems the CPU and network usage patterns have changed with the `2.5.0.0.4` release, which seems to be related:
![Screenshot 2024-06-28 at 10 21 52 AM](https://github.com/stacks-network/stacks-core/assets/2747302/375a4fad-38e7-4b2f-828c-cff1bc0c1921)
![Screenshot 2024-06-28 at 10 22 18 AM](https://github.com/stacks-network/stacks-core/assets/2747302/4b264156-f255-4ad7-8914-74f5b346b8a8)

**Steps To Reproduce**
1. Deploy a mainnet stacks node
2. Write a script to occasionally hit some endpoints and record the time to respond.

**Comment by wileyj** [comment]
#4940

**Comment by kantai** [comment]
The fix for this made it into https://github.com/stacks-network/stacks-core/releases/tag/2.5.0.0.5 -- closing!
