### ISSUE TITLE
[Nakamoto] getsortition.rs try_handle_request does not actually attempt to return the last winning sortition correctly

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#4938]
This function should be returning the last sortition with the winning commit. However, note the if statement returns none for the last_sortition_ch when the fetched block snapshot does not contain a winning sortition. Later in the signer we attempt to use this non existent consensus hash to find the last winning soritition which will of course always fail. Update getsortition.rs to properly fetch the last winning sortition. This can either be fixed inside getsortition.rs or in the chainstate.
See the following relevant sections:
https://github.com/stacks-network/stacks-core/blob/19f753b173cad722d48873e72bf26a9a27010918/stackslib/src/net/api/getsortition.rs#L216

https://github.com/stacks-network/stacks-core/blob/19f753b173cad722d48873e72bf26a9a27010918/stacks-signer/src/chainstate.rs#L359

**Comment by jcnelson** [comment]
I can take this

**Comment by jcnelson** [comment]
So, just a heads up, this is not what the node's API contract of this endpoint is.  The API contract is to return data about a _specific_ sortition, given one of a set of possible identifiers for it.  If that sortition happens to be empty, then no data will be returned.

But, I can change the node to always return the consensus hash of the last sortition with a winner

**Comment by jcnelson** [comment]
Here you go.  https://github.com/stacks-network/stacks-core/pull/4939

Can you add test coverage to this and verify that it does what the signer expects it to do?

**Comment by jferrant** [comment]
> Here you go. #4939
> 
> Can you add test coverage to this and verify that it does what the signer expects it to do?

Will do!
