### ISSUE TITLE
[Testing] multiple signers and miners each with their own stacks node

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#4974]
Have signers each using their own node and have multiple competing miners. Ensure that they can continue to sign and propagate their signatures amongst each other to append to blocks.

**Comment by saralab** [comment]
@charlie to update with Naka-3 setup details

**Comment by CharlieC3** [comment]
Details for the current Naka-3 test setup are as follows:

**Stacks Blockchain API**
* Multiple readers
* 1 writer
* Postgresql DB

**Stacks Core Miner A**
* [monitor](https://github.com/hirosystems/stacks-regtest-env/blob/feat/signer/stacking/monitor.ts)
* 3 signers
* [stacker](https://github.com/hirosystems/stacks-regtest-env/blob/feat/signer/stacking/stacking.ts)
* 1 miner running [latest from develop](https://github.com/stacks-network/stacks-core/commit/202b45cc65b88a15d31a33370e47850cf98d7c21)
* [tx-broadcaster](https://github.com/hirosystems/stacks-regtest-env/blob/feat/signer/stacking/tx-broadcaster.ts)

**Stacks Core Miner B**
* 1 miner running [latest from develop](https://github.com/stacks-network/stacks-core/commit/202b45cc65b88a15d31a33370e47850cf98d7c21)

Miners A and B have each other configured in the `bootstrap_node` property for discovery. Those with access can view their respective config.toml's here:
[Miner A](https://github.com/hirosystems/k8s/blob/main/manifests/api/regtest/api-nakamoto-3/prd/use4/stacks-core-configmap.yaml#L11)
[Miner B](https://github.com/hirosystems/k8s/blob/main/manifests/api/regtest/api-nakamoto-3/prd/use4/stacks-core-configmap.yaml#L201)
