### ISSUE TITLE
[testing] Force a stacks fork with two competing miners.

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#4975]
Force a signer to sign a block A. Before the signed block A is mined. Have a competing miner which won its tenure propose a block B. What should the correct behaviour be? I think you need to ensure that signers maintain a canonical chain by signing only blocks that build on the previously signed last block, but in the case of two proposed blocks that have not technically been mined yet...this would induce a fork. not sure what the next block signed should be...I assume miner 2 will then propose another block Block C and it will be build off their own block B. But what if it handed off to a third miner before this happened ...that miner could choose to build off of either block, no? I think actually he should build off of block A...but I am not 100% sure. Will both blocks be appended? I think @kantai  might need to answer this.

**Comment by kantai** [comment]
Implemented in #5034 -- this PR implements whole tenure forks, but it is worth also testing partial tenure forks as well.

**Comment by hstove** [comment]
Closing as #5034 has been merged.
