### ISSUE TITLE
Contracts and contract-calls which invoke Clarity 3 features are regularly published and executed with correct values on a multi-miner testnet

### ISSUE THREAD

**Issue by saralab** [stacks-network/stacks-core#4983]
This is the success criteria for 3.0 Testnet Readiness. Once a stable multi-miner testnet is established, ensure that the Contracts and contract-calls which invoke Clarity 3 features are regularly published and executed with correct values on this Testnet.

**Comment by BowTiedRadone** [comment]
Follow-up on this issue: @moodmosaic and I have successfully developed a high-frequency system that is capable of deploying contracts and making contract calls with valid arguments 24/7 on multi-miner testnets. The system can now run against any Stacks network, and we’re ready to target any in the future.

**Comment by BowTiedRadone** [comment]
Update: 20 valid `Clarity3` contracts have been added to the deployment pool and **will be deployed during the next fuzzer run**.
