### ISSUE TITLE
[Nakamoto] Miner gets stuck building on the same parent over and over due to inherent race conditions

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-core#5030]
Consider the following race condition:

1. Miner A produces block B and goes to sleep
2. Signers S1, S2, and S3 produce signatures S1(A, B), S2(A, B), and S3(A, B)
3. A sortition happens, and miner C produces block D
4. Signers S1, S2, and S3 produce signatures S1(C, D), S2(C, D), and S3(C, D)
5. Miner A's node stores S1(C, D), S2(C, D), and S3(C, D), overwriting S1(A, B), S2(A, B), and S3(A, B) 
6. Miner A wakes up, and declares that S1(C, D), S2(C, D), and S3(C, D) aren't the signatures it was expecting and tries to mine again
7. Miner A tries to produce B' and goes to sleep, repeating the process

The race condition happens in step 5 -- miner A can lose signer signatures if miner B can get its block signed before miner A's signatures arrive.  This outcome is mitigated by #4998, because then miner A would at least get its missing signatures, but miner A really needs to check to see if its tenure is still active before trying again in step 7.

This issue reports that the miner thread currently does not check that its tenure is still active.

**Comment by kantai** [comment]
> This issue reports that the miner thread currently does not check that its tenure is still active.

Doesn't the miner thread check the burnchain tip before mining blocks?

```
        self.check_burn_tip_changed(&burn_db)?;
```

**Comment by jcnelson** [comment]
It gets stuck waiting for signatures.
