### ISSUE TITLE
CI test failing for tests::signer::v0::empty_sortition

### ISSUE THREAD

**Issue by wileyj** [stacks-network/stacks-core#5032]
`tests::signer::v0::empty_sortition` passes locally, but consistently fails when run in github actions. 

opening this to track, otherwise not a high priority

**Comment by obycode** [comment]
Can confirm, this passes locally for me as well.

**Comment by wileyj** [comment]
adding some more tests from @obycode 
```
tests::epoch_25::microblocks_disabled
tests::nakamoto_integrations::follower_bootup
tests::signer::v0::forked_tenure_invalid
tests::signer::v0::multiple_miners
tests::signer::v0::miner_forking
```

**Comment by wileyj** [comment]
@jbencin

**Comment by obycode** [comment]
Looks like this one too: `tests::nakamoto_integrations::mock_mining`

**Comment by wileyj** [comment]
#5054 addresses all except for `tests::nakamoto_integrations::mock_mining` which will be addressed in separate PR per @kantai

**Comment by kantai** [comment]
#5063 should address the last one 🤞
