### ISSUE TITLE
[Miner] miner issues TenureExtend block if the first Nakamoto sortition is empty

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-core#5046]
In the event that the first sortition in the Nakamoto epoch has no winner, all miners issue a `TenureExtend` tenure-change transaction instead of a `TenureChange` transaction, leading to a chain halt.

**Comment by diwakergupta** [comment]
From the referenced commits, looks like this was fixed. Can this be closed @jcnelson @saralab ?
