### ISSUE TITLE
Add an integration test for duplicate signers on the same network

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#5077]
We should have a test that spins up multiple signers with the same private key and ensure the system can handle signatures from duplicate signers. The first submitted valid signature should take precedence.

**Comment by jbencin** [comment]
Also, check that duplicate signer produces identical signatures, and recovered pubkeys are the same. This is expected because we derive the ECDSA nonce from the message hash instead of an RNG

**Comment by jcnelson** [comment]
Can we close this?

**Comment by jbencin** [comment]
Closed by #5108
