### ISSUE TITLE
Make sure Atlas tracks attachments updates from BNSv2 as part of the Nakamoto upgrade

### ISSUE THREAD

**Issue by 314159265359879** [stacks-network/stacks-core#5109]
**Is your feature request related to a problem? Please describe.**
Atlas currently tracks the BNS contract for changes. It should start tracking BNSv2 attachement updates. 

**Describe the solution you'd like**
See quotes in additional context

**Describe alternatives you've considered**
n.a.

**Additional context**
Partial quote from @bilalanees98 ([source](https://github.com/Trust-Machines/BNS-V2/issues/33#issuecomment-2100421490))
> * Nodes are configured to track attachment events generated through (print …) statements on a smart-contract
> * Once attachments are logged, atlas contacts peers to check if any of them have the attachment data. This data is stored in something called AtlasDB
> * By default they are set to track `.bns` events [here](https://github.com/stacks-network/stacks-core/blob/master/stackslib/src/net/atlas/mod.rs#L106)
>   
>   * This will have to be updated, nodes will have to track the new bns contract

Quote from @jcnelson ([source](https://github.com/Trust-Machines/BNS-V2/issues/33#issuecomment-2218425930))
> > By default they are set to track .bns events here
> > 
> > * This will have to be updated, nodes will have to track the new bns contract
> 
> Can you open an issue on the Stacks blockchain repo so this gets done prior to BNSv2 going live? Presumably, this would be part of the Nakamoto release.

**Comment by jcnelson** [comment]
Seems this won't be necessary since BNSv2 stores the zone file directly in the contract.
