### ISSUE TITLE
Integration Test - Non standard transaction, but not invalid being anchored

### ISSUE THREAD

**Issue by ASuciuX** [stacks-network/stacks-core#5129]
A transaction that normally wouldn't be picked by miners is picked and anchored by a miner. The only type of transaction like this is a transaction without fees (which won't get to mempool, but can be anchored by the miner directly).

Steps:
1. create transaction with 0 fees, signed
2. as miner, anchor it
3. check for any unexpected behaviour

Also, what are the limits in size of a transaction? Same as the block?

**Comment by janniks** [comment]
Optional: Check for possible reasons for `dropped_problematic` if those can be "mined" and chain will still continue?

Optinoal: RE Radone: get data from `0` (genesis) block in Clarity.

**Comment by ASuciuX** [comment]
Limits for [block](https://github.com/stacks-network/stacks-core/blob/8b2a5cf442ffcc4ba8cc7bb5a25ce713ff34e5d2/stackslib/src/chainstate/stacks/tests/block_construction.rs#L1300) and for [transactions](https://github.com/stacks-network/stacks-core/blob/8b2a5cf442ffcc4ba8cc7bb5a25ce713ff34e5d2/stackslib/src/chainstate/stacks/tests/block_construction.rs#L1830) are tested.

Problematic transactions are tested [here](https://github.com/stacks-network/stacks-core/blob/8b2a5cf442ffcc4ba8cc7bb5a25ce713ff34e5d2/stackslib/src/chainstate/stacks/tests/block_construction.rs#L3769).
