### ISSUE TITLE
Nakamoto miner building from not the latest parent block

### ISSUE THREAD

**Issue by obycode** [stacks-network/stacks-core#5145]
Running in naka-3 with branch `fix/5136-signer-block-state-tracking` (as of commit 3047b5f10f9aa1e0ea0464433956ff6455574122), I am seeing some strange behavior from the Nakamoto miner. In the first tenure of epoch 3.0, burn block 131, the canonical tip is block 128, but the miner is attempting to reorg this block and mine another block 128. The signers correctly reject these block proposals, so we end up with no blocks in tenure 131. Complete logs can be found [here](https://grafana.hiro.tools/explore?schemaVersion=1&panes=%7B%22ggs%22:%7B%22datasource%22:%22--%20Mixed%20--%22,%22queries%22:%5B%7B%22refId%22:%22Regtest%20Naka-3%20Logs%22,%22expr%22:%22%7Bnamespace%3D%5C%22regtest-api%5C%22,%20pod_name%3D~%5C%22regtest-stacks-blockchain-nakamoto-3-miner-0%7Cregtest-stacks-blockchain-nakamoto-3-miner-1%7Cregtest-stacks-blockchain-nakamoto-3-miner-2%5C%22,%20level%3D~%5C%22error%7Cinfo%7Cwarn%5C%22,%20container_name%3D~%5C%22stacks-blockchain%5C%22%7D%20%21%3D%20%60Failed%20to%20store%20chunk%20for%20StackerDB%60%20%21%3D%20%60Rejected%20Nakamoto%20block%60%20%21%3D%20%60hyper::%60%20%7C%20json%20%7C%20message%20%21%3D%20%60Mempool:%20unexecutable:%20drop%20tx%60%20%7C%20message%20%21%3D%20%60Handled%20StacksHTTPRequest%60%20%7C%20thread%20%21%3D%20%60p2p-%280.0.0.0:20444,0.0.0.0:20443%29%60%20%7C%20line_format%20%60%7B%7B.container_name%7D%7D:%7B%7B.thread%7D%7D%20-%20%7B%7B.message%7D%7D%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221725502800000%22,%22to%22:%221725502830000%22%7D%7D%7D&orgId=1).

Miner Logs:
```log
09/04/2024, 10:20:19.201 PM	stacks-blockchain:miner.eb2ccfb4b40488c3f0e17f9b51d19f4001ff3196f2eb03b1244f01ba861f0f4f - Error while gathering signatures: SignersRejected. Will try mining again.
09/04/2024, 10:20:17.361 PM	stacks-blockchain:miner.eb2ccfb4b40488c3f0e17f9b51d19f4001ff3196f2eb03b1244f01ba861f0f4f - SignCoordinator: beginning to watch for block signatures OR posted blocks.
09/04/2024, 10:20:17.206 PM	stacks-blockchain:miner.eb2ccfb4b40488c3f0e17f9b51d19f4001ff3196f2eb03b1244f01ba861f0f4f - Miner: Assembled block #28 for signer set proposal: 394338327c7e10fc5580f1551e923632d0af51fa9b6a361cf58c5d2b7ed03b57, with 2 txs
09/04/2024, 10:20:17.121 PM	stacks-blockchain:miner.eb2ccfb4b40488c3f0e17f9b51d19f4001ff3196f2eb03b1244f01ba861f0f4f - Miner: mined Nakamoto block
```

Signer logs:
```log
09/04/2024, 10:20:18.110 PM	signer:signer_runloop:30000 - Cycle #6 Signer #2: Block proposal invalid
09/04/2024, 10:20:18.110 PM	signer:signer_runloop:30000 - Miner is not building off of most recent tenure, but a tenure they attempted to reorg has already mined blocks, and there is no local knowledge for that tenure's block timing.
09/04/2024, 10:20:17.995 PM	signer:signer_runloop:30000 - Most recent miner's tenure does not build off the prior sortition, checking if this is valid behavior
09/04/2024, 10:20:17.673 PM	signer:signer_runloop:30000 - Cycle #6 Signer #2: received a block proposal for a new block. Submit block for validation. 
09/04/2024, 10:20:17.133 PM	signer:signer_runloop:30000 - Cycle #6 Signer #2: Received a new burn block event for block height 131
```

**Comment by jferrant** [comment]
This seems to be due to the miner submitting an invalid block commit built off of 129 and not successfully rbf'ing it before 130 is mined. Therefore it always keeps trying to rebuild off the wrong commit and signers correctly reject it.
