### ISSUE TITLE
[Network] inbound neighbor walk is broken

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-core#5159]
It appears that there has been a behavioral regression in the node's neighbor walk algorithm.  It ought to be the case that if node A contacts node B, then node B should attempt to contact node A, and if successful, add node A to its outbound peer set (making it eligible for data pushed from node B, and eligible for enumeration in response to a `GetNeighbors` p2p message).  This isn't happening anymore.

**Comment by saralab** [comment]
Misconfiguration could be the problem.  Still needs to be evaluated on a testnet
