### ISSUE TITLE
`miner_signature_hash` should include `pox_treatment` BitVec

### ISSUE THREAD

**Issue by hstove** [stacks-network/stacks-core#5216]
When constructing `miner_signature_hash` for a Nakamoto block, the `pox_treatment` BitVec is not included. While this is included in `signer_signature_hash`, not including this in the miner's sighash can result in inconsistent blocks that signers are signing over.

**Comment by jcnelson** [comment]
I think this is intentional.  The signers decide among themselves what the signer liveness bitvec should be, not the miner.

**Comment by jcnelson** [comment]
(cc @kantai)
