### ISSUE TITLE
Unable to get tenure-info in the first block of a tenure

### ISSUE THREAD

**Issue by hugocaillard** [stacks-network/stacks-core#5228]
**Describe the bug**

`(get-tenure-info? <prop> stacks-block-height)` always returns `none` because of [this condition](https://github.com/stacks-network/stacks-core/blob/0b4f3b2fb9151dfd4dec3846929f4c11cf29d00d/clarity/src/vm/functions/database.rs#L1072-L1074).

Because of this, the tenure-info can not be none in the block 0 of a tenure, and there is a different behavior between block 0 and block 1 of tenure.
Similarly, `(get-tenure-info? <prop> (- stacks-block-height u1))` would return the info of the previous tenure in block 0, but it would return the info of the current tenure in block 1 of this new tenure.

**Expected behavior**

To be confirmed: It should be possible to get the tenure info in the first block (block 0) of a tenure

**Comment by obycode** [comment]
See https://github.com/stacks-network/stacks-core/issues/5246. We decided that this should be the expected behavior.
