### ISSUE TITLE
Epoch 3.0 Testnet Config 

### ISSUE THREAD

**Issue by saralab** [stacks-network/stacks-core#5287]
Placeholder to track Testnet 3.0 config: https://github.com/stacks-network/stacks-core/discussions/5006#discussion-6974703

**Comment by kantai** [comment]
Candidate block: 56,457.

This would be approximately 11am Eastern time, October 10.

This is around 150 blocks before the next prepare phase.

**Comment by kantai** [comment]
Configuration set in 1a08c1368
