### ISSUE TITLE
Test "Tenure extend for bad tenures" on Nakamoto Testnet

### ISSUE THREAD

**Issue by aldur** [stacks-network/stacks-core#5477]
Ref #5452.

**Comment by obycode** [comment]
You could probably trigger the bad block commit scenario by adjusting the config on one miner, setting the `block_commit_delay_ms` to `0` in the `[miner]` section and  setting `max_rbf` in the `[burnchain]` section to `100`. That miner would then likely have a bad block commit every time it wins and the previous good miner should extend.

**Comment by aldur** [comment]
Assigning this to @jferrant to check that we have triggered the specific issue and it works as expected.
