### ISSUE TITLE
Have miners report their version

### ISSUE THREAD

**Issue by aldur** [stacks-network/stacks-core#5517]
Signers broadcast their version as part of their standard operations. This makes it easy to measure how release updates are adopted across the network. 

This feature proposes adding the same to miners.

**Describe the solution you'd like**
Ideally, miners would report their version when communicating with the rest of the network. They could also do that when mining a new block (e.g. in a memo or similar).

**Additional context**
I _think_ miners right now report something related to the `StacksEpochId`, which does not change for minor/point releases.

https://github.com/stacks-network/stacks-core/blob/7267cd0fd58bdcf94c7f32f411ea162dd9a83b36/stacks-common/src/types/mod.rs#L74

**Comment by jcnelson** [comment]
We discussed this at length in the past and determined it was a privacy
violation.

What we have done instead is to bump the block version (which is not
consensus-critical), so we can tell what the minimum version of the miner
is.

**Comment by diwakergupta** [comment]
> We discussed this at length in the past and determined it was a privacy violation.

Can you link to any prior written discussion and decision on this? Also, even if a decision had been reached in the past, that does not mean the decision can't or shouldn't be revisited. Needing to know if miners have upgraded is a recurring issue and IMO it merits having a proper solution in place. 

One thought: version reporting could be configurable, on by default and if miners don't want it, they can just turn the reporting off.

**Comment by jcnelson** [comment]
It was discussed in one of the past blockchain meetings years ago.  Your suggestion of making it configurable was also discussed, and ultimately dropped in favor of using the block version byte.

I continue to stand by the status quo.

Also, I reject the premise of adding telemetry surreptitiously and making it opt-out.  Not only is the legality questionable (doesn't this violate the GDPR?), but I also think it's unethical.  No one asked to be spied on.

**Comment by aldur** [comment]
> What we have done instead is to bump the block version (which is not consensus-critical), so we can tell what the minimum version of the miner is.

Are there other constraints around bumping this e.g. on point releases?

**Comment by jcnelson** [comment]
It's done on an as-needed basis, but certainly not every release. That
would defeat the point.

**Comment by aldur** [comment]
Closing this for the time being -- we might revisit it later.
