### ISSUE TITLE
[CI] Resolve "no tests to run" error

### ISSUE THREAD

**Issue by obycode** [stacks-network/stacks-core#5554]
When CI runs on a PR, we will sometimes see "error: no tests to run". See [here](https://github.com/stacks-network/stacks-core/actions/runs/12243565052/job/34154159640?pr=5550) for example.

**Comment by obycode** [comment]
This has been happening recently with several of the `net::server::tests` tests.
- [P2P Tests / Integration Tests (net::server::tests::test_http_10_threads_getinfo)](https://github.com/stacks-network/stacks-core/issues/5554#logs)
- [P2P Tests / Integration Tests (net::server::tests::test_http_10_threads_getblock)](https://github.com/stacks-network/stacks-core/issues/5554#logs)
- [P2P Tests / Integration Tests (net::server::tests::test_http_too_many_clients)](https://github.com/stacks-network/stacks-core/issues/5554#logs)
- [P2P Tests / Integration Tests (net::server::tests::test_http_slow_client)](https://github.com/stacks-network/stacks-core/issues/5554#logs)

**Comment by aldur** [comment]
@jcnelson reports this is due to the test path being wrong in the CI yaml.
